import csv
import hashlib
import json
import math
import os
import subprocess
from pathlib import Path

ROOT = Path.cwd()
PYTHON_NOTE = "Generated by tools/wing_full_angle/build_wing_full_angle_assets.py"
XFOIL = Path(r"E:\tiltrotor\tools\external\xfoil\xfoil.exe")
EXPECTED_XFOIL_SHA = "C17342F84AE260C2B11A74CD0E2FB8189A5F8954C6BB7A8467A0F27055C7FAEA"

DIRS = [
    "references/wing_full_angle", "tools/wing_full_angle", "data/wing_full_angle/airfoils",
    "data/wing_full_angle/xfoil/raw", "data/wing_full_angle/xfoil/parsed",
    "data/wing_full_angle/tm88373_digitized", "data/wing_full_angle/full_angle_candidates",
    "data/wing_full_angle/full_angle_selected", "validation/wing_full_angle/full_angle",
    "validation/wing_full_angle/wake_strip", "docs/wing_full_angle",
]
for d in DIRS:
    (ROOT / d).mkdir(parents=True, exist_ok=True)

def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest().upper()

def pdf_info(path):
    info = {"page_count": "UNKNOWN", "text_extractable": "UNKNOWN", "pdf_header_valid": False}
    try:
        with open(path, "rb") as f:
            info["pdf_header_valid"] = f.read(5) == b"%PDF-"
    except FileNotFoundError:
        return info
    try:
        from pypdf import PdfReader
        reader = PdfReader(str(path))
        info["page_count"] = len(reader.pages)
        sample = ""
        for page in reader.pages[: min(3, len(reader.pages))]:
            try:
                sample += page.extract_text() or ""
            except Exception:
                pass
        info["text_extractable"] = bool(sample.strip())
    except Exception as exc:
        info["text_extractable"] = f"ERROR: {exc}"
    return info

def write_csv(path, rows, fields):
    with open(ROOT / path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for row in rows:
            w.writerow({k: row.get(k, "") for k in fields})

# Source manifest, including failed CR-114614 endpoint and existing repo PDFs.
sources = [
    {"name":"NASA_TM_88373.pdf","report":"NASA TM-88373","nasa_id":"19870005749","url":"https://ntrs.nasa.gov/api/citations/19870005749/downloads/19870005749.pdf","local_path":"references/wing_full_angle/NASA_TM_88373.pdf","status":"DOWNLOADED"},
    {"name":"NASA_CR_114614.pdf","report":"NASA CR-114614","nasa_id":"19730022217","url":"https://ntrs.nasa.gov/api/citations/19730022217/downloads/19730022217.pdf","local_path":"references/wing_full_angle/NASA_CR_114614.pdf","status":"DOWNLOAD_404_RETRY_REQUIRED"},
    {"name":"NASA_CR_176970.pdf","report":"NASA CR-176970","nasa_id":"19860020297","url":"https://ntrs.nasa.gov/api/citations/19860020297/downloads/19860020297.pdf","local_path":"references/wing_full_angle/NASA_CR_176970.pdf","status":"DOWNLOADED"},
    {"name":"NASA_TM_X_62407.pdf","report":"NASA TM-X-62407","nasa_id":"EXISTING_REPO_SOURCE","url":"repository","local_path":"references/NASA_TM_X_62407.pdf","status":"EXISTING"},
    {"name":"NASA_TM_81244.pdf","report":"NASA TM-81244","nasa_id":"EXISTING_REPO_SOURCE","url":"repository","local_path":"references/NASA_TM_81244.pdf","status":"EXISTING"},
    {"name":"NUAA_main_paper.pdf","report":"NUAA main paper","nasa_id":"NOT_APPLICABLE","url":"repository","local_path":"references/NUAA_main_paper.pdf","status":"EXISTING"},
]
manifest_rows = []
for s in sources:
    p = ROOT / s["local_path"]
    row = dict(s)
    if p.exists():
        st = p.stat()
        meta = pdf_info(p)
        row.update({"size_bytes": st.st_size, "sha256": sha256(p), **meta})
    else:
        row.update({"size_bytes": 0, "sha256": "", "page_count": "MISSING", "text_extractable": "", "pdf_header_valid": False})
    manifest_rows.append(row)
write_csv("data/wing_full_angle/source_manifest.csv", manifest_rows,
          ["name","report","nasa_id","url","local_path","status","size_bytes","sha256","pdf_header_valid","page_count","text_extractable"])

reqs = [
    ("airfoil coordinate source","required","NACA 64A223 surrogate generated in task script","ASSUMED","Geometry partial because direct coordinate table was not recovered."),
    ("XFOIL Reynolds range","required","0.6e6, 1.0e6, 1.4e6","DERIVED","Matches TM-88373 stated range in initial anchors."),
    ("Mach range","required","0 and 0.10","ASSUMED","Low-speed tiltrotor wing section envelope for initial database."),
    ("low-angle Cl/Cd/Cm","required","XFOIL clean-airfoil attempts plus analytic fallback only for database continuity","MIXED","Accepted XFOIL rows are marked separately from fallback rows."),
    ("near -90 deg Cl/Cd/Cm","required","initial_source_anchors.csv / TM-88373","REFERENCE_TEXT","Direct text anchors, not full curve digitization."),
    ("positive deep stall","required","mirrored engineering extension","ASSUMED","No positive near-normal digitization completed."),
    ("full-angle periodic closure","required","explicit -180/180 closure points","DERIVED","Continuity checked numerically."),
    ("wake strip coverage","required","strip overlap with rotor wake disk projection","ASSUMED","CR-176970 geometry anchors used where available; CR-114614 unavailable."),
    ("rotor induced velocity input","required","existing rotor.inducedVelocity and rotor.eT","CODE_ONLY","Does not alter legacy rotor interface."),
    ("default model selector","required","P.wing.fullAngleModelEnabled = 0","CODE_ONLY","Legacy remains default."),
]
write_csv("data/wing_full_angle/parameter_requirement_matrix.csv",
          [{"item":a,"required":b,"source":c,"source_class":d,"status":"PARTIAL" if d in ("ASSUMED","MIXED") else "AVAILABLE","notes":e} for a,b,c,d,e in reqs],
          ["item","required","source","source_class","status","notes"])

# Airfoil candidate scores.
candidates = [
    {"candidate":"NACA 64A223","coordinate_traceability":2,"low_angle_calculability":4,"full_angle_evidence":4,"near_90_evidence":5,"tiltrotor_relevance":5,"unsupported_extrapolation":2,"score":22,"selected":1,"notes":"Selected due to TM-88373 near-vertical test chain. Coordinate route remains surrogate/partial."},
    {"candidate":"NACA 23012","coordinate_traceability":4,"low_angle_calculability":4,"full_angle_evidence":2,"near_90_evidence":1,"tiltrotor_relevance":2,"unsupported_extrapolation":3,"score":16,"selected":0,"notes":"Good coordinate availability but weaker direct near-vertical tiltrotor wake chain."},
]
write_csv("data/wing_full_angle/airfoil_candidate_scores.csv", candidates,
          ["candidate","coordinate_traceability","low_angle_calculability","full_angle_evidence","near_90_evidence","tiltrotor_relevance","unsupported_extrapolation","score","selected","notes"])

# NACA-like surrogate coordinate generator: not an exact 6-series pressure distribution.
def naca4_like(m=0.02, p=0.4, t=0.23, n=161):
    beta = [math.pi * i / (n - 1) for i in range(n)]
    x = [(1 - math.cos(b)) / 2 for b in beta]
    yt = [5*t*(0.2969*math.sqrt(max(xi,0)) - 0.1260*xi - 0.3516*xi**2 + 0.2843*xi**3 - 0.1015*xi**4) for xi in x]
    yc=[]; dyc=[]
    for xi in x:
        if xi < p:
            yc_i = m/(p*p)*(2*p*xi - xi*xi)
            dy_i = 2*m/(p*p)*(p - xi)
        else:
            yc_i = m/((1-p)*(1-p))*((1 - 2*p) + 2*p*xi - xi*xi)
            dy_i = 2*m/((1-p)*(1-p))*(p - xi)
        yc.append(yc_i); dyc.append(dy_i)
    theta = [math.atan(v) for v in dyc]
    upper=[]; lower=[]
    for xi,yti,yci,th in zip(x,yt,yc,theta):
        upper.append((xi - yti*math.sin(th), yci + yti*math.cos(th)))
        lower.append((xi + yti*math.sin(th), yci - yti*math.cos(th)))
    coords = list(reversed(upper)) + lower[1:]
    return coords, upper, lower
coords, upper, lower = naca4_like()
airfoil_path = ROOT / "data/wing_full_angle/airfoils/naca64a223_surrogate.dat"
with open(airfoil_path, "w", encoding="ascii", newline="\n") as f:
    f.write("NACA 64A223 SURROGATE - 23 pct thickness, 2 pct camber, 40 pct camber-location; not original 6-series coordinates\n")
    for x,y in coords:
        f.write(f"{x: .8f} {y: .8f}\n")
# Geometry checks.
thickness = [u[1]-l[1] for u,l in zip(upper,lower)]
imax = max(range(len(thickness)), key=lambda i: thickness[i])
geom = [{"airfoil":"NACA 64A223 surrogate","point_count":len(coords),"te_gap":abs(upper[-1][1]-lower[-1][1]),"max_thickness_ratio":thickness[imax],"max_thickness_x":upper[imax][0],"leading_edge_closed":abs(upper[0][1]-lower[0][1]) < 1e-8,"self_intersection_check":"NOT_PERFORMED","xfoil_load_test":"SEE_XFOIL_MANIFEST","notes":"Surrogate geometry; AIRFOIL_GEOMETRY gate is PARTIAL."}]
write_csv("data/wing_full_angle/airfoil_geometry_checks.csv", geom,
          ["airfoil","point_count","te_gap","max_thickness_ratio","max_thickness_x","leading_edge_closed","self_intersection_check","xfoil_load_test","notes"])

# XFOIL attempts: clean airfoil only. Flap deflections are recorded as not geometrically attempted.
xfoil_manifest = []
xfoil_rows = []
xfoil_hash_ok = XFOIL.exists() and sha256(XFOIL) == EXPECTED_XFOIL_SHA
for Re in [0.6e6, 1.0e6, 1.4e6]:
    for Mach in [0.0, 0.10]:
        run_dir = ROOT / f"data/wing_full_angle/xfoil/raw/Re{int(Re):07d}_M{Mach:.2f}_clean"
        run_dir.mkdir(parents=True, exist_ok=True)
        polar = run_dir / "polar.txt"
        inp = run_dir / "xfoil.inp"
        log = run_dir / "xfoil.log"
        commands = [
            f"LOAD {airfoil_path}", "PANE", "OPER", f"VISC {Re:.0f}", f"MACH {Mach:.3f}", "ITER 220", "PACC", str(polar), "", "ASEQ -25 25 1", "PACC", "", "QUIT"
        ]
        inp.write_text("\n".join(commands) + "\n", encoding="ascii")
        status = "NOT_RUN"
        err = ""
        if xfoil_hash_ok:
            try:
                with open(inp, "rb") as fin, open(log, "wb") as fout:
                    proc = subprocess.run([str(XFOIL)], stdin=fin, stdout=fout, stderr=subprocess.STDOUT, cwd=str(run_dir), timeout=90)
                status = "RAN" if proc.returncode == 0 else f"EXIT_{proc.returncode}"
            except subprocess.TimeoutExpired:
                status = "TIMEOUT"
                err = "XFOIL timeout at 90 s"
        else:
            status = "XFOIL_HASH_OR_EXISTENCE_FAIL"
        accepted = 0
        if polar.exists():
            for line in polar.read_text(errors="ignore").splitlines():
                parts = line.split()
                if len(parts) >= 5:
                    try:
                        a, cl, cd, cdp, cm = [float(parts[i]) for i in range(5)]
                    except ValueError:
                        continue
                    xfoil_rows.append({"Re":Re,"Mach":Mach,"flap_deg":0,"alpha_deg":a,"CL":cl,"CD":cd,"Cm":cm,"source":"XFOIL_CLEAN_SURROGATE_GEOMETRY"})
                    accepted += 1
        xfoil_manifest.append({"Re":Re,"Mach":Mach,"flap_deg":0,"status":status,"accepted_points":accepted,"input":str(inp.relative_to(ROOT)),"polar":str(polar.relative_to(ROOT)),"log":str(log.relative_to(ROOT)),"error":err})
for flap in [20,40,50,60]:
    xfoil_manifest.append({"Re":"0.6e6-1.4e6","Mach":"0/0.10","flap_deg":flap,"status":"NOT_ATTEMPTED_GEOMETRY_ROUTE_UNVERIFIED","accepted_points":0,"input":"","polar":"","log":"","error":"XFOIL flap geometry modification for surrogate 64A223 not validated; not fabricated."})
write_csv("data/wing_full_angle/xfoil/parsed/xfoil_clean_polars.csv", xfoil_rows,
          ["Re","Mach","flap_deg","alpha_deg","CL","CD","Cm","source"])
write_csv("data/wing_full_angle/xfoil/xfoil_attempt_manifest.csv", xfoil_manifest,
          ["Re","Mach","flap_deg","status","accepted_points","input","polar","log","error"])

# Build selected full-angle database. Prefer Re=1e6, Mach=0 XFOIL where available.
low = {round(r["alpha_deg"]): r for r in xfoil_rows if abs(r["Re"]-1.0e6)<1 and abs(r["Mach"]-0.0)<1e-9}
def analytic_low(a):
    ar = math.radians(a)
    cl = max(min(0.15 + 5.2*ar, 1.35), -1.35)
    cd = 0.025 + 0.055*cl*cl
    cm = -0.03
    return cl, cd, cm, "ANALYTIC_LOW_ANGLE_FALLBACK"
anchors = {
    -180:(0.0,0.08,0.0,"PERIODIC_CLOSURE_ASSUMED"),
    -140:(-0.75,1.35,0.03,"FLAT_PLATE_BRIDGE_ASSUMED"),
    -105:(-0.20,1.28,0.02,"TM88373_DIGITIZED_ANCHOR_APPROX"),
    -96:(-0.05,1.16,0.01,"TM88373_TEXT_OPPOSITE_ROTATION_ANCHOR"),
    -85:(0.10,1.09,0.0,"TM88373_TEXT_60DEG_FLAP_ANCHOR"),
    -80:(0.15,1.10,-0.01,"TM88373_TEXT_XV15_WAKE_ANCHOR"),
    -75:(0.20,1.20,-0.02,"TM88373_RANGE_ENDPOINT_ANCHOR"),
}
# Add low-angle points from -25..25.
for a in range(-25,26):
    if a in low:
        rr=low[a]; anchors[a]=(rr["CL"], rr["CD"], rr["Cm"], "XFOIL_CLEAN_SURROGATE_GEOMETRY")
    else:
        anchors[a]=(*analytic_low(a),)
# Positive side mirrored/flat-plate assumptions.
for a in [75,80,85,96,105,140,180]:
    neg = -a
    if neg in anchors:
        cl,cd,cm,src = anchors[neg]
        anchors[a]=(-cl, cd, -cm, "ASSUMED_POSITIVE_DEEP_STALL_MIRROR_OF_" + src)
anchors[0] = anchors.get(0, (*analytic_low(0),))
# Linear interpolation across sparse anchors on each coefficient.
keys = sorted(anchors)
rows=[]
for a in range(-180,181):
    if a in anchors:
        cl,cd,cm,src=anchors[a]
    else:
        lo=max(k for k in keys if k<a); hi=min(k for k in keys if k>a)
        t=(a-lo)/(hi-lo)
        cl=anchors[lo][0]*(1-t)+anchors[hi][0]*t
        cd=anchors[lo][1]*(1-t)+anchors[hi][1]*t
        cm=anchors[lo][2]*(1-t)+anchors[hi][2]*t
        src=f"LINEAR_BRIDGE_{anchors[lo][3]}__TO__{anchors[hi][3]}"
    rows.append({"alpha_deg":a,"alpha_rad":math.radians(a),"CL":cl,"CD":max(cd,0.0),"Cm":cm,"source":src})
write_csv("data/wing_full_angle/full_angle_selected/wing_full_angle_database.csv", rows,
          ["alpha_deg","alpha_rad","CL","CD","Cm","source"])
# Candidate summaries and simple validation metrics.
max_jump = 0.0
max_slope = 0.0
prev = None
for row in rows:
    if prev:
        jump = math.sqrt((row["CL"]-prev["CL"])**2 + (row["CD"]-prev["CD"])**2 + (row["Cm"]-prev["Cm"])**2)
        max_jump = max(max_jump, jump)
        max_slope = max(max_slope, jump / math.radians(1))
    prev = row
validation = [{"metric":"max_adjacent_coefficient_jump_per_deg","value":max_jump,"passed":max_jump < 0.25}, {"metric":"max_combined_slope_per_rad","value":max_slope,"passed":max_slope < 20}, {"metric":"periodic_closure_error","value":abs(rows[0]["CL"]-rows[-1]["CL"])+abs(rows[0]["CD"]-rows[-1]["CD"])+abs(rows[0]["Cm"]-rows[-1]["Cm"]),"passed":True}]
write_csv("validation/wing_full_angle/full_angle/full_angle_database_checks.csv", validation,
          ["metric","value","passed"])
Path(ROOT/"data/wing_full_angle/full_angle_selected/database_metadata.json").write_text(json.dumps({"database_id":"wing_full_angle_v0_partial_20260702","selected_airfoil":"NACA 64A223","geometry_status":"SURROGATE_PARTIAL","xfoil_executable":str(XFOIL),"xfoil_sha256_ok":xfoil_hash_ok,"note":PYTHON_NOTE}, indent=2), encoding="utf-8")
print("Generated full wing assets")
print(f"XFOIL rows: {len(xfoil_rows)}")
print(f"Max coefficient jump: {max_jump:.6g}")
