function tableOut = crosscheck_control_derivatives( ...
        pointId,directControlTable,derivativeResult, ...
        torqueLinearModel,commandLinearModel,trimReport,P13)
%CROSSCHECK_CONTROL_DERIVATIVES Convert B matrices back to load derivatives.
% Direct physical controls and angle-command nacelle inputs remain distinct.

contract = control_stability_interface_contract();
ref = derivativeResult.reference;
mp9 = mass_properties(trimReport.condition.betaM,P13.base);
mp13 = trimReport.point.eomOut.massProperties;
denominators = [ref.qbar*ref.S;ref.qbar*ref.S; ...
    ref.qbar*ref.S;ref.qbar*ref.S*ref.b; ...
    ref.qbar*ref.S*ref.c;ref.qbar*ref.S*ref.b];
rows = repmat(empty_row(),0,1);

for controlIndex = 1:numel(contract.nineInputNames)
    controlName = contract.nineInputNames{controlIndex};
    direct = directControlTable( ...
        strcmp(directControlTable.perturbationName,controlName) & ...
        directControlTable.stepLevel == 2,:);
    column13 = contract.nineToThirteenInputColumns(controlIndex);

    load9 = [mp9.mass*derivativeResult.B9(1:3,controlIndex); ...
        mp9.I*derivativeResult.B9(4:6,controlIndex)];
    load13Torque = [ ...
        mp13.mass*torqueLinearModel.B13Torque(1:3,column13); ...
        mp13.I*torqueLinearModel.B13Torque(4:6,column13)];
    load13Command = [ ...
        mp13.mass*commandLinearModel.B13Command(1:3,column13); ...
        mp13.I*commandLinearModel.B13Command(4:6,column13)];
    coefficient9 = load9./denominators;
    coefficient13Torque = load13Torque./denominators;
    coefficient13Command = load13Command./denominators;

    for componentIndex = 1:height(direct)
        row = empty_row();
        row.pointId = pointId;
        row.controlName = controlName;
        row.controlUnit = 'rad';
        row.coefficientName = direct.coefficientName{componentIndex};
        row.directCoefficientDerivative = ...
            direct.coefficientDerivative(componentIndex);
        row.B9RecoveredCoefficientDerivative = coefficient9(componentIndex);
        row.B13TorqueRecoveredCoefficientDerivative = ...
            coefficient13Torque(componentIndex);
        row.B13CommandRecoveredCoefficientDerivative = ...
            coefficient13Command(componentIndex);
        row.relativeDifferenceB9 = relative_difference( ...
            row.directCoefficientDerivative, ...
            row.B9RecoveredCoefficientDerivative);
        row.relativeDifferenceB13Torque = relative_difference( ...
            row.directCoefficientDerivative, ...
            row.B13TorqueRecoveredCoefficientDerivative);
        row.relativeDifferenceB13Command = relative_difference( ...
            row.directCoefficientDerivative, ...
            row.B13CommandRecoveredCoefficientDerivative);
        row.statusB9 = status_value(row.directCoefficientDerivative, ...
            row.B9RecoveredCoefficientDerivative);
        row.statusB13Torque = status_value( ...
            row.directCoefficientDerivative, ...
            row.B13TorqueRecoveredCoefficientDerivative);
        row.statusB13Command = status_value( ...
            row.directCoefficientDerivative, ...
            row.B13CommandRecoveredCoefficientDerivative);
        row.interfaceInterpretation = [ ...
            'columns 1-8 are direct physical controls in both 13-state ' ...
            'interfaces; columns 9-10 are torque or angle command and ' ...
            'are not included in this physical-control comparison'];
        rows(end+1,1) = row; %#ok<AGROW>
    end
end
tableOut = struct2table(rows);
end

function value = relative_difference(reference,candidate)
value = abs(candidate-reference)/max(abs(reference),1e-10);
end

function status = status_value(reference,candidate)
absoluteDifference = abs(candidate-reference);
relativeDifference = relative_difference(reference,candidate);
if relativeDifference <= 5e-3 || absoluteDifference <= 1e-6
    status = 'FULL_CROSSCHECK';
else
    status = 'PARTIAL_CROSSCHECK';
end
end

function row = empty_row()
row = struct('pointId','','controlName','','controlUnit','', ...
    'coefficientName','','directCoefficientDerivative',NaN, ...
    'B9RecoveredCoefficientDerivative',NaN, ...
    'B13TorqueRecoveredCoefficientDerivative',NaN, ...
    'B13CommandRecoveredCoefficientDerivative',NaN, ...
    'relativeDifferenceB9',NaN, ...
    'relativeDifferenceB13Torque',NaN, ...
    'relativeDifferenceB13Command',NaN, ...
    'statusB9','','statusB13Torque','','statusB13Command','', ...
    'interfaceInterpretation','');
end
