function grid = generic_trim_design_grid()
%GENERIC_TRIM_DESIGN_GRID Frozen nine-point design-feasibility set.

d2r = pi/180;
betaDeg = [15;15;15;45;45;45;75;75;75];
speedMps = [10;20;30;25;35;45;40;60;80];
mode = {'helicopter_longitudinal';'helicopter_longitudinal'; ...
    'helicopter_longitudinal';'conversion_longitudinal'; ...
    'conversion_longitudinal';'conversion_longitudinal'; ...
    'airplane_longitudinal';'airplane_longitudinal'; ...
    'airplane_longitudinal'};
pointId = arrayfun(@(b,v) sprintf('B%02d_V%03d',b,v), ...
    betaDeg,speedMps,'UniformOutput',false);
condition = arrayfun(@(v,b) struct('V',v,'betaM',b*d2r,'gamma',0), ...
    speedMps,betaDeg,'UniformOutput',false);
grid = table(pointId,betaDeg,speedMps,mode,condition);
grid.Properties.Description = ['DESIGN_FEASIBILITY_SET; prescribed ' ...
    'research targets, not external measurement data or a validated corridor'];
end
