function results = run_nacelle_model_hierarchy_study(outputDir)
%RUN_NACELLE_MODEL_HIERARCHY_STUDY Three-point frozen-model comparison.
%
% This analysis is deliberately read-only with respect to physical models
% and defaults.  It compares:
%   1) the legacy 9-state model with fixed (quasi-static) nacelle angle;
%   2) the 13-state command model on its symmetric invariant manifold; and
%   3) the same 13-state model with independent left/right nacelle motion.
%
% The frozen C2 parameter set is reused without optimization.  The study
% points and trim values are read from the archived PR5B result table.

if nargin < 1 || isempty(outputDir)
    error('run_nacelle_model_hierarchy_study:OutputRequired', ...
        'An explicit output directory is required.');
end
if ~exist(outputDir,'dir'), mkdir(outputDir); end
rawDir = fullfile(outputDir,'raw_data');
if ~exist(rawDir,'dir'), mkdir(rawDir); end

[P13,parameterManifest] = params_generic_trim_optimized();
sourceTable = readtable(fullfile('results','generic_trim_pr5b', ...
    'deliverables','MODEL_C2_EFFECTIVE_OPTIMIZED_RESULTS.csv'), ...
    'TextType','string');
pointIds = ["B15_V020";"B45_V035";"B75_V080"];

pointRows = cell(numel(pointIds),25);
responseRows = cell(2*numel(pointIds),26);
rateRows = cell(numel(pointIds),11);
eigenRows = {};
linearModels = cell(numel(pointIds),1);
simulations = cell(numel(pointIds),2);

for k = 1:numel(pointIds)
    pointId = pointIds(k);
    index = find(sourceTable.pointId == pointId,1);
    if isempty(index)
        error('run_nacelle_model_hierarchy_study:MissingPoint', ...
            'Archived C2 point %s is missing.',pointId);
    end
    if sourceTable.status(index) ~= "CREDIBLE"
        error('run_nacelle_model_hierarchy_study:NonCrediblePoint', ...
            'Point %s is not an archived credible trim.',pointId);
    end

    betaM = deg2rad(sourceTable.betaMDeg(index));
    speed = sourceTable.speedMps(index);
    theta = deg2rad(sourceTable.thetaDeg(index));
    x9 = [speed*cos(theta);0;speed*sin(theta);zeros(4,1);theta;0];
    u7 = deg2rad([sourceTable.collectiveDeg(index);0; ...
        sourceTable.cyclicLongDeg(index);0;0; ...
        sourceTable.elevatorDeg(index);0]);
    x13 = [x9;betaM;betaM;0;0];
    u10Command = [u7(1:4);0;u7(5:7);betaM;betaM];

    [f9,out9] = tiltrotor_eom(x9,u7,betaM,P13.base);
    [f13,out13] = tiltrotor_eom_13x10_command( ...
        x13,u10Command,P13);
    initialResidual9 = norm(f9(1:6));
    initialResidual13 = norm(f13([1:6,10:13]));

    scales = [0.1,1,10];
    A9set = cell(3,1); B9set = cell(3,1);
    A13set = cell(3,1); B13set = cell(3,1);
    for j = 1:3
        Pstep = P13.base;
        Pstep.linear.dx = P13.base.linear.dx*scales(j);
        Pstep.linear.du = P13.base.linear.du*scales(j);
        [A9set{j},B9set{j},report9] = ...
            linearize_numeric(x9,u7,betaM,Pstep);
        [A13set{j},B13set{j},report13] = ...
            linearize_13x10_command_numeric( ...
            x13,u10Command,P13,scales(j));
        if ~(report9.finite && report13.finiteReal)
            error('run_nacelle_model_hierarchy_study:NonFiniteLinearModel', ...
                'Non-finite linear model at %s and scale %g.', ...
                pointId,scales(j));
        end
    end
    A9 = A9set{2}; B9 = B9set{2};
    A13 = A13set{2}; B13 = B13set{2};
    transform = berger13_symdiff_transform(A13,B13,'ANGLE_COMMAND');
    Asd = transform.A;
    commonInputColumns = [1:4,6:8];
    parityA = norm(A13(1:9,1:9)-A9,'fro');
    parityB = norm(B13(1:9,commonInputColumns)-B9,'fro');
    stepVariation9 = max( ...
        norm([A9set{1}-A9,B9set{1}-B9],'fro'), ...
        norm([A9set{3}-A9,B9set{3}-B9],'fro')) / ...
        max(norm([A9,B9],'fro'),eps);
    stepVariation13 = max( ...
        norm([A13set{1}-A13,B13set{1}-B13],'fro'), ...
        norm([A13set{3}-A13,B13set{3}-B13],'fro')) / ...
        max(norm([A13,B13],'fro'),eps);

    longitudinal = [1,3,5,8,10,12];
    lateralDirectional = [2,4,6,7,9,11,13];
    crossBlockNorm = norm(Asd(longitudinal,lateralDirectional),'fro') + ...
        norm(Asd(lateralDirectional,longitudinal),'fro');
    angleSymRigidNorm = norm(Asd(1:6,10));
    angleDiffRigidNorm = norm(Asd(1:6,11));
    rateSymRigidNorm = norm(Asd(1:6,12));
    rateDiffRigidNorm = norm(Asd(1:6,13));
    diffAngleYLR = Asd([2,4,6],11).';

    hRate = 1e-4;
    xSymRate = x13; xSymRate(12:13) = hRate;
    [~,outSymRate] = tiltrotor_eom_13x10_command( ...
        xSymRate,u10Command,P13);
    xDiffRate = x13; xDiffRate(12) = -hRate; ...
        xDiffRate(13) = hRate;
    [~,outDiffRate] = tiltrotor_eom_13x10_command( ...
        xDiffRate,u10Command,P13);
    reactionSym = (outSymRate.MactuatorReaction- ...
        out13.MactuatorReaction)/hRate;
    reactionDiff = (outDiffRate.MactuatorReaction- ...
        out13.MactuatorReaction)/hRate;
    gyroSym = (outSymRate.MnacelleRateGyro- ...
        out13.MnacelleRateGyro)/hRate;
    gyroDiff = (outDiffRate.MnacelleRateGyro- ...
        out13.MnacelleRateGyro)/hRate;

    trimReport.x13 = x13;
    trimReport.u10Command = u10Command;
    trimReport.condition = struct('V',speed,'betaM',betaM,'gamma',0);
    trimReport.credible = true;
    trimReport.status = 'CREDIBLE';
    trimReport.inputContract = 'ANGLE_COMMAND';

    amplitudes = [2,1]*pi/180;
    inputTypes = {'betaSym','betaDiff'};
    for j = 1:2
        caseDef = struct('name',sprintf('%s_%s',pointId,inputTypes{j}), ...
            'duration',3,'dt',0.05,'startTime',0.5, ...
            'amplitude',amplitudes(j),'inputType',inputTypes{j});
        [fine,fineMetric,history,convergenceChange,coarseDt,fineDt] = ...
            converged_response(trimReport,P13,caseDef);
        simulations{k,j} = fine;
        writetable(history,fullfile(rawDir, ...
            sprintf('%s_%s.csv',pointId,inputTypes{j})));
        row = 2*(k-1)+j;
        responseRows(row,:) = {char(pointId),sourceTable.betaMDeg(index), ...
            speed,inputTypes{j},rad2deg(amplitudes(j)),fineDt,coarseDt, ...
            fineMetric.validDurationSeconds, ...
            fineMetric.maxBetaSymDeviationRad, ...
            fineMetric.maxBetaDiffRad, ...
            fineMetric.maxLongitudinalVelocityDeviationMps, ...
            fineMetric.maxLateralVelocityDeviationMps, ...
            fineMetric.maxPitchRateRadPerSecond, ...
            fineMetric.maxRollRateRadPerSecond, ...
            fineMetric.maxYawRateRadPerSecond, ...
            fineMetric.maxPitchAttitudeDeviationRad, ...
            fineMetric.maxRollAttitudeDeviationRad, ...
            fineMetric.maxAbsLateralForceN, ...
            fineMetric.maxAbsRollMomentNm, ...
            fineMetric.maxAbsPitchMomentNm, ...
            fineMetric.maxAbsYawMomentNm, ...
            fineMetric.maxRigidAccelerationNorm, ...
            fineMetric.maximumDynamicTrimDeparture, ...
            convergenceChange, ...
            fine.quantitativeClaimAllowed,fine.finiteReal};
    end

    eig9 = eig(A9);
    eig13SymmetricManifold = eig(Asd(longitudinal,longitudinal));
    eig13 = eig(A13);
    eigenRows = [eigenRows; eigenvalue_rows(pointId,'9_STATE',eig9); ...
        eigenvalue_rows(pointId,'13_STATE_SYMMETRIC_MANIFOLD', ...
        eig13SymmetricManifold); ...
        eigenvalue_rows(pointId,'13_STATE_INDEPENDENT',eig13)]; %#ok<AGROW>

    pointRows(k,:) = {char(pointId),sourceTable.betaMDeg(index),speed, ...
        sourceTable.thetaDeg(index),initialResidual9,initialResidual13, ...
        parityA,parityB,stepVariation9,stepVariation13,crossBlockNorm, ...
        angleSymRigidNorm,angleDiffRigidNorm,rateSymRigidNorm, ...
        rateDiffRigidNorm,diffAngleYLR(1),diffAngleYLR(2), ...
        diffAngleYLR(3),size(A9,1),size(A13,1), ...
        numel(eig13)-numel(eig9),P13.base.rotor.Jpolar, ...
        out9.massProperties.minInertiaEigenvalue, ...
        out13.massProperties.minInertiaEigenvalue, ...
        all(isfinite([A9(:);B9(:);A13(:);B13(:)]))};
    rateRows(k,:) = {char(pointId),sourceTable.betaMDeg(index),speed, ...
        reactionSym(1),reactionSym(2),reactionSym(3), ...
        reactionDiff(1),reactionDiff(2),reactionDiff(3), ...
        norm(gyroSym),norm(gyroDiff)};
    linearModels{k} = struct('pointId',pointId,'A9',A9,'B9',B9, ...
        'A13',A13,'B13',B13,'symdiff',transform, ...
        'A9Scales',{A9set},'B9Scales',{B9set}, ...
        'A13Scales',{A13set},'B13Scales',{B13set});
end

pointSummary = cell2table(pointRows,'VariableNames', ...
    {'pointId','betaMDeg','speedMps','thetaDeg', ...
    'initialRigidResidualNorm9','initialDynamicResidualNorm13', ...
    'commonAParityFrobenius','commonBParityFrobenius', ...
    'maximumStepVariation9','maximumStepVariation13', ...
    'symmetricDifferentialCrossBlockNorm', ...
    'symmetricAngleToRigidDerivativeNorm', ...
    'differentialAngleToRigidDerivativeNorm', ...
    'symmetricRateToRigidDerivativeNorm', ...
    'differentialRateToRigidDerivativeNorm', ...
    'dVdotDBetaDiff','dPdotDBetaDiff','dRdotDBetaDiff', ...
    'quasiStaticStateCount','dynamicStateCount','addedStateCount', ...
    'rotorPolarInertiaKgM2','minimumInertiaEigenvalue9', ...
    'minimumInertiaEigenvalue13','finiteReal'});
responseSummary = cell2table(responseRows,'VariableNames', ...
    {'pointId','betaMDeg','speedMps','inputType','amplitudeDeg', ...
    'archiveDt','precedingDt','validDurationSeconds', ...
    'maxBetaSymDeviationRad','maxBetaDiffRad', ...
    'maxLongitudinalVelocityDeviationMps','maxLateralVelocityDeviationMps', ...
    'maxPitchRateRadPerSecond','maxRollRateRadPerSecond', ...
    'maxYawRateRadPerSecond','maxPitchAttitudeDeviationRad', ...
    'maxRollAttitudeDeviationRad','maxAbsLateralForceN', ...
    'maxAbsRollMomentNm','maxAbsPitchMomentNm','maxAbsYawMomentNm', ...
    'maxRigidAccelerationNorm','maximumDynamicTrimDeparture', ...
    'coarseFinePeakChange','quantitativeClaimAllowed','finiteReal'});
rateContribution = cell2table(rateRows,'VariableNames', ...
    {'pointId','betaMDeg','speedMps', ...
    'reactionSymXNmPerRadPerSec','reactionSymYNmPerRadPerSec', ...
    'reactionSymZNmPerRadPerSec','reactionDiffXNmPerRadPerSec', ...
    'reactionDiffYNmPerRadPerSec','reactionDiffZNmPerRadPerSec', ...
    'gyroSymNormNmPerRadPerSec','gyroDiffNormNmPerRadPerSec'});
eigenvalueSummary = cell2table(eigenRows,'VariableNames', ...
    {'pointId','layer','rootIndex','realPartPerSecond', ...
    'imagPartRadPerSecond','naturalFrequencyRadPerSecond'});

writetable(pointSummary,fullfile(outputDir, ...
    'MODEL_HIERARCHY_POINT_SUMMARY.csv'));
writetable(responseSummary,fullfile(outputDir, ...
    'MODEL_HIERARCHY_RESPONSE_METRICS.csv'));
writetable(rateContribution,fullfile(outputDir, ...
    'NACELLE_RATE_DIRECT_CONTRIBUTION.csv'));
writetable(eigenvalueSummary,fullfile(outputDir, ...
    'MODEL_HIERARCHY_EIGENVALUES.csv'));

results.pointSummary = pointSummary;
results.responseSummary = responseSummary;
results.rateContribution = rateContribution;
results.eigenvalueSummary = eigenvalueSummary;
results.linearModels = linearModels;
results.simulations = simulations;
results.parameterManifest = parameterManifest;
results.parameterSet = 'GENERIC_TRIM_OPTIMIZED_C2_FROZEN';
results.pointCount = numel(pointIds);
results.layerCount = 3;
results.physicsCodeModified = false;
results.defaultParametersModified = false;
results.finiteReal = all(pointSummary.finiteReal) && ...
    all(responseSummary.finiteReal);
results.claimBoundary = ['Internal comparison for a generic low-order ' ...
    'component model.  The command actuator is prescribed and one-way; ' ...
    'no external hinge-load feedback or mechanical-jam load is modeled.'];
save(fullfile(outputDir,'MODEL_HIERARCHY_RESULTS.mat'),'results','-v7');
end

function [simulation,metric,history,change,coarseDt,fineDt] = ...
        converged_response(trimReport,P13,caseDef)
dtValues = [0.05,0.025,0.0125,0.00625,0.003125];
previousDef = caseDef;
previousDef.dt = dtValues(1);
previous = simulate_berger13_case(trimReport,P13,previousDef);
[previousMetric,~] = response_metrics(previous,trimReport,P13);
simulation = [];
metric = [];
history = [];
change = Inf;
coarseDt = NaN;
fineDt = NaN;
for k = 2:numel(dtValues)
    currentDef = caseDef;
    currentDef.dt = dtValues(k);
    current = simulate_berger13_case(trimReport,P13,currentDef);
    [currentMetric,currentHistory] = ...
        response_metrics(current,trimReport,P13);
    change = scaled_peak_change(previousMetric,currentMetric);
    if change <= 0.02
        simulation = current;
        metric = currentMetric;
        history = currentHistory;
        coarseDt = dtValues(k-1);
        fineDt = dtValues(k);
        break;
    end
    previousMetric = currentMetric;
end
if isempty(simulation)
    error('run_nacelle_model_hierarchy_study:TimeStepNotConverged', ...
        ['Case %s did not satisfy the 2%% adjacent-step peak gate ' ...
        'through dt=0.003125 s.'],caseDef.name);
end
simulation.timeStepConverged = true;
simulation.timeStepTolerance = 0.02;
simulation.quantitativeClaimAllowed = ...
    simulation.quantitativeClaimAllowed && simulation.timeStepConverged;
end

function [metric,history] = response_metrics(sim,trimReport,P13)
n = size(sim.x,1);
rigidAccelerationNorm = NaN(n,1);
dynamicDeparture = NaN(n,1);
pitchMoment = NaN(n,1);
for k = 1:n
    [xdot,out] = tiltrotor_eom_13x10_command( ...
        sim.x(k,:).',sim.u(k,:).',P13);
    rigidAccelerationNorm(k) = norm(xdot(1:6));
    dynamicDeparture(k) = norm(xdot([1:6,10:13]));
    pitchMoment(k) = out.Mtotal(2);
end
last = sim.validPrefixEndIndex;
idx = 1:last;
deviation = sim.x-trimReport.x13(:).';
metric.validDurationSeconds = sim.time(last);
metric.maxBetaSymDeviationRad = max(abs( ...
    sim.betaSym(idx)-trimReport.x13(10)),[],'omitnan');
metric.maxBetaDiffRad = max(abs(sim.betaDiff(idx)),[],'omitnan');
metric.maxLongitudinalVelocityDeviationMps = ...
    max(abs(deviation(idx,1)),[],'omitnan');
metric.maxLateralVelocityDeviationMps = ...
    max(abs(deviation(idx,2)),[],'omitnan');
metric.maxPitchRateRadPerSecond = max(abs(deviation(idx,5)),[],'omitnan');
metric.maxRollRateRadPerSecond = max(abs(deviation(idx,4)),[],'omitnan');
metric.maxYawRateRadPerSecond = max(abs(deviation(idx,6)),[],'omitnan');
metric.maxPitchAttitudeDeviationRad = ...
    max(abs(deviation(idx,8)),[],'omitnan');
metric.maxRollAttitudeDeviationRad = ...
    max(abs(deviation(idx,7)),[],'omitnan');
metric.maxAbsLateralForceN = max(abs( ...
    sim.lateralForceRollYawMoment(idx,1)),[],'omitnan');
metric.maxAbsRollMomentNm = max(abs( ...
    sim.lateralForceRollYawMoment(idx,2)),[],'omitnan');
metric.maxAbsPitchMomentNm = max(abs(pitchMoment(idx)),[],'omitnan');
metric.maxAbsYawMomentNm = max(abs( ...
    sim.lateralForceRollYawMoment(idx,3)),[],'omitnan');
metric.maxRigidAccelerationNorm = ...
    max(rigidAccelerationNorm(idx),[],'omitnan');
metric.maximumDynamicTrimDeparture = ...
    max(dynamicDeparture(idx),[],'omitnan');
history = table(sim.time,sim.x(:,1),sim.x(:,2),sim.x(:,3), ...
    sim.x(:,4),sim.x(:,5),sim.x(:,6),sim.x(:,7),sim.x(:,8), ...
    sim.betaSym,sim.betaDiff, ...
    sim.lateralForceRollYawMoment(:,1), ...
    sim.lateralForceRollYawMoment(:,2),pitchMoment, ...
    sim.lateralForceRollYawMoment(:,3),rigidAccelerationNorm, ...
    dynamicDeparture,sim.guardValid, ...
    'VariableNames',{'timeSeconds','uMps','vMps','wMps', ...
    'pRadPerSecond','qRadPerSecond','rRadPerSecond','phiRad','thetaRad', ...
    'betaSymRad','betaDiffRad','lateralForceN','rollMomentNm', ...
    'pitchMomentNm','yawMomentNm','rigidAccelerationNorm', ...
    'dynamicTrimDeparture','analysisGuardValid'});
end

function change = scaled_peak_change(coarse,fine)
names = {'maxBetaSymDeviationRad','maxBetaDiffRad', ...
    'maxLongitudinalVelocityDeviationMps','maxLateralVelocityDeviationMps', ...
    'maxPitchRateRadPerSecond','maxRollRateRadPerSecond', ...
    'maxYawRateRadPerSecond','maxPitchAttitudeDeviationRad', ...
    'maxRollAttitudeDeviationRad','maxAbsRollMomentNm', ...
    'maxAbsPitchMomentNm','maxAbsYawMomentNm', ...
    'maxRigidAccelerationNorm','maximumDynamicTrimDeparture'};
floors = [1e-6,1e-6,1e-6,1e-6,1e-6,1e-6,1e-6,1e-6,1e-6, ...
    1,1,1,1e-6,1e-6];
values = zeros(numel(names),1);
for k = 1:numel(names)
    a = coarse.(names{k});
    b = fine.(names{k});
    values(k) = abs(b-a)/max([abs(a),abs(b),floors(k)]);
end
change = max(values);
end

function rows = eigenvalue_rows(pointId,layer,values)
rows = cell(numel(values),6);
for k = 1:numel(values)
    rows(k,:) = {char(pointId),layer,k,real(values(k)),imag(values(k)), ...
        abs(values(k))};
end
end
