function P = params_xv15_public()
%PARAMS_XV15_PUBLIC XV-15 public geometry/limits profile.
% This profile starts from params_nominal() and replaces only public,
% traceable mass, geometry, rotor speed, airfoil, control-surface maximum
% deflection, and engine-power reference values. It is not a complete XV-15
% mathematical model or flight-test-validated aircraft database.
%
% Primary sources:
% - NASA SP-2000-4517, Appendix A, "XV-15 Characteristics", PDF pp. 156-157,
%   printed pp. 131-132.
% - NASA TM-81177, notation table and summary, PDF pp. 4-6.

P = params_nominal();

lb_to_kg = 0.45359237;
ft_to_m = 0.3048;
in_to_m = 0.0254;
sqft_to_sqm = 0.09290304;
d2r = pi / 180;

P.meta.parameterProfile = 'XV15_PUBLIC_GEOMETRY_PROFILE';
P.meta.parameterProfileStatus = ...
    'PUBLIC_GEOMETRY_AND_LIMITS_ONLY_NOT_FULL_XV15_DATABASE';
P.meta.primarySources = { ...
    'NASA SP-2000-4517 Appendix A XV-15 Characteristics'; ...
    'NASA TM-81177 Wind-Tunnel Tests of the XV-15 Tilt Rotor Aircraft'};
P.meta.profileScope = ['Only public mass, geometry, rotor speed, airfoil, ' ...
    'control-surface maximum deflection, and engine-power reference fields ' ...
    'are replaced. Inertia, CG, nacelle mass, control derivatives, SCAS, ' ...
    'blade dynamic parameters, and tail locations remain non-XV15-sourced.'];
P.meta.unitSystem = 'SI_WITH_ANGLES_IN_RADIANS';

%% Mass/weight references
P.mass.m = 13000 * lb_to_kg; % design gross weight, 13000 lb
P.mass.emptyActual_kg = 10083 * lb_to_kg;
P.mass.actualGrossAtEngineStart_kg = 13248 * lb_to_kg;
P.mass.fuelReference_kg = 1436 * lb_to_kg;
P.mass.researchInstrumentation_kg = 1148 * lb_to_kg;

P.mass.publicReferenceSource = ...
    'NASA_SP_2000_4517_APPENDIX_A_XV15_CHARACTERISTICS_PDF_156_157_PRINTED_131_132';
P.mass.retainedConceptStatus = struct( ...
    'I0', 'ASSUMED_CONCEPT_NOT_XV15_SOURCED', ...
    'KI', 'ASSUMED_CONCEPT_NOT_XV15_SOURCED', ...
    'mNac', 'ASSUMED_CONCEPT_NOT_XV15_SOURCED', ...
    'RH_mass', 'ASSUMED_CONCEPT_NOT_XV15_SOURCED');

%% Wing public geometry
P.wing.S = 169.0 * sqft_to_sqm;
P.wing.b = (32 + 2/12) * ft_to_m;
P.wing.c = 5.25 * ft_to_m;
P.wing.airfoil = 'NACA 64A223';
P.wing.sweep = -6.5 * d2r;
P.wing.dihedral = 2.0 * d2r;
P.wing.aspectRatioReference = 6.12;
P.wing.sweepDihedralStatus = ...
    'STORED_PUBLIC_METADATA_NOT_YET_APPLIED_TO_CURRENT_AERODYNAMIC_COORDINATES';
P.wing.publicReferenceSource = ...
    'NASA_SP_2000_4517_APPENDIX_A_XV15_CHARACTERISTICS_PDF_156_PRINTED_131';
P.wing.retainedConceptStatus = struct( ...
    'CL0', 'ASSUMED_OR_CALIBRATED_CONCEPT_NOT_XV15_SOURCED', ...
    'CLalpha', 'ASSUMED_OR_CALIBRATED_CONCEPT_NOT_XV15_SOURCED', ...
    'CLmax', 'ASSUMED_OR_CALIBRATED_CONCEPT_NOT_XV15_SOURCED', ...
    'CD0', 'ASSUMED_OR_CALIBRATED_CONCEPT_NOT_XV15_SOURCED', ...
    'kInduced', 'ASSUMED_OR_CALIBRATED_CONCEPT_NOT_XV15_SOURCED', ...
    'Cm0', 'CALIBRATED_EFFECTIVE_PARAMETER_NOT_XV15_SOURCED', ...
    'Cmalpha', 'ASSUMED_CONCEPT_NOT_XV15_SOURCED', ...
    'CLaileron', 'ASSUMED_CONCEPT_NOT_XV15_SOURCED', ...
    'Cmaileron', 'ASSUMED_CONCEPT_NOT_XV15_SOURCED');

%% Horizontal tail public geometry
P.htail.span = (12 + 10/12) * ft_to_m;
P.htail.S = 50.25 * sqft_to_sqm;
P.htail.c = (3 + 11/12) * ft_to_m;
P.htail.airfoil = 'NACA 64A015';
P.htail.aspectRatioReference = 3.27;
P.htail.rACStatus = ...
    'NON_XV15_SOURCED_ASSUMED_GEOMETRY_UNTIL_DIGITIZED';
P.htail.publicReferenceSource = ...
    'NASA_SP_2000_4517_APPENDIX_A_XV15_CHARACTERISTICS_PDF_156_PRINTED_131';
P.htail.retainedConceptStatus = struct( ...
    'rAC', 'ASSUMED_GEOMETRY_NOT_XV15_SOURCED', ...
    'CLalpha', 'ASSUMED_OR_CALIBRATED_CONCEPT_NOT_XV15_SOURCED', ...
    'CLelevator', 'CALIBRATED_EFFECTIVE_PARAMETER_NOT_XV15_SOURCED', ...
    'downwashAlpha', 'CALIBRATED_EFFECTIVE_PARAMETER_NOT_XV15_SOURCED', ...
    'incidence', 'CALIBRATED_EFFECTIVE_PARAMETER_NOT_XV15_SOURCED');

%% Twin vertical tails public geometry
% SP-2000-4517 gives vertical-tail area as total area; the current code
% models two tails, so store half of the public total area per side.
P.vtail.SEach = 0.5 * 50.5 * sqft_to_sqm;
P.vtail.c = 3.72 * ft_to_m; % mean aerodynamic chord
P.vtail.airfoil = 'NACA 0009';
P.vtail.aspectRatioReference = 2.33;
P.vtail.positionStatus = 'ASSUMED_UNTIL_DIGITIZED_NOT_XV15_SOURCED';
P.vtail.publicReferenceSource = ...
    'NASA_SP_2000_4517_APPENDIX_A_XV15_CHARACTERISTICS_PDF_156_PRINTED_131';
P.vtail.retainedConceptStatus = struct( ...
    'xAC', 'ASSUMED_GEOMETRY_NOT_XV15_SOURCED', ...
    'yAC', 'ASSUMED_GEOMETRY_NOT_XV15_SOURCED', ...
    'zAC', 'ASSUMED_GEOMETRY_NOT_XV15_SOURCED', ...
    'CYbeta', 'ASSUMED_CONCEPT_NOT_XV15_SOURCED', ...
    'CYrudder', 'ASSUMED_CONCEPT_NOT_XV15_SOURCED');

%% Rotor/proprotor public geometry and speed references
P.rotor.R = 0.5 * 25.0 * ft_to_m;
P.rotor.Nb = 3;
P.rotor.chord = 14.0 * in_to_m;
P.rotor.Ib = P.rotor.bladeMass * P.rotor.R^2 / 3;
P.rotor.Sblade = P.rotor.bladeMass * P.rotor.R / 2;
P.rotor.derivedAssumptionStatus = ...
    'RECOMPUTED_FROM_ASSUMED_BLADE_MASS_AND_PUBLIC_RADIUS_NOT_XV15_SOURCED';
P.rotor.solidityReference = 0.089;
P.rotor.diskLoadingReference_lb_ft2 = 13.2;
P.rotor.OmegaHelicopter = 589 * 2*pi / 60;
P.rotor.OmegaAirplane = 517 * 2*pi / 60;
P.rotor.Omega = P.rotor.OmegaHelicopter;
P.rotor.OmegaScheduleStatus = ...
    'XV15_HAS_589_RPM_HELICOPTER_AND_517_RPM_AIRPLANE_BUT_MODEL_STILL_USES_SINGLE_OMEGA';
P.rotor.twistGeometricSpinnerToTip = 36 * d2r;
P.rotor.delta3 = -15 * d2r;
P.rotor.twistMappingStatus = ...
    'PUBLIC_TOTAL_TWIST_STORED_NOT_MAPPED_TO_CURRENT_LINEAR_TWIST_MODEL';
P.rotor.publicReferenceSource = ...
    'NASA_SP_2000_4517_APPENDIX_A_XV15_CHARACTERISTICS_PDF_156_PRINTED_131';
P.rotor.retainedConceptStatus = struct( ...
    'RH_hub', 'ASSUMED_GEOMETRY_NOT_XV15_SOURCED', ...
    'pivotX', 'ASSUMED_GEOMETRY_NOT_XV15_SOURCED', ...
    'pivotY', 'ASSUMED_GEOMETRY_NOT_XV15_SOURCED', ...
    'pivotZ', 'ASSUMED_GEOMETRY_NOT_XV15_SOURCED', ...
    'bladeMass', 'ASSUMED_CONCEPT_NOT_XV15_SOURCED', ...
    'Ib', 'DERIVED_FROM_ASSUMED_BLADE_MASS_NOT_XV15_SOURCED', ...
    'Sblade', 'DERIVED_FROM_ASSUMED_BLADE_MASS_NOT_XV15_SOURCED');

%% Powerplant public reference values only
P.powerplant.engineModel = 'Lycoming LTC1K-4K modified T53-L-13B';
P.powerplant.engineCount = 2;
P.powerplant.contingencyPower_shp = 1802;
P.powerplant.takeoffPower_shp = 1550;
P.powerplant.maxContinuousPower_shp = 1250;
P.powerplant.helicopterModeTransmissionLimit_shp = 1160;
P.powerplant.constraintStatus = ...
    'REFERENCE_ONLY_NOT_APPLIED_TO_TRIM_OR_POWER_CONSTRAINT_SOLVER';
P.powerplant.publicReferenceSource = ...
    'NASA_SP_2000_4517_APPENDIX_A_XV15_CHARACTERISTICS_PDF_156_PRINTED_131';

%% Control and nacelle conversion references
P.control.flapMax = 75 * d2r;
P.control.flaperonMax = 47 * d2r;
P.control.flapFlaperonStatus = ...
    'PUBLIC_REFERENCE_LIMITS_ONLY_AILERON_LIMIT_NOT_OVERWRITTEN';

P.nacelle.sourceAngleConvention = 'XV15_PUBLIC: 90deg helicopter, 0deg airplane';
P.nacelle.modelAngleConvention = 'CODE: betaM=0 helicopter, betaM=pi/2 airplane';
P.nacelle.rateNormal = 7.5 * d2r;
P.nacelle.rateSlow = 1.5 * d2r;
P.nacelle.publicReferenceSource = ...
    'NASA_SP_2000_4517_APPENDIX_A_XV15_CHARACTERISTICS_AND_CONVERSION_DESCRIPTION';
end
