function report = check_trim_mode_boundaries()
%CHECK_TRIM_MODE_BOUNDARIES Retain evidence against unverified mode splicing.

condition = struct('V',45,'betaM',pi/4,'gamma',0);
expect_mode_error(@() trim_berger13_symmetric( ...
    condition,params_berger13(),struct()), ...
    'trim_berger13_symmetric:ExplicitModeRequired');
expect_mode_error(@() trim_reference_rotor_symmetric( ...
    condition,params_berger13(),struct()), ...
    'trim_reference_rotor_symmetric:ExplicitModeRequired');

report = audit_trim_mode_boundaries();
assert(report.auditCompleted, ...
    'One or more trim-mode boundary evaluations did not complete.');
assert(height(report.boundarySummary) == 2, ...
    'Expected one 30 deg and one 60 deg boundary summary.');
assert(all(ismember(report.boundarySummary.boundaryDeg,[30;60])), ...
    'The audited handoff angles changed unexpectedly.');
assert(~report.continuityDemonstrated && ~report.claimAllowed, ...
    ['The current three-definition handoffs must not be presented as a ' ...
     'continuous control law without reviewed replacement evidence.']);
assert(report.allPassed, ...
    'The expected continuity-not-demonstrated classification changed.');
end

function expect_mode_error(fun,identifier)
try
    fun();
catch ME
    assert(strcmp(ME.identifier,identifier), ...
        'Expected %s, received %s.',identifier,ME.identifier);
    return;
end
error('check_trim_mode_boundaries:MissingExpectedError', ...
    'Expected error %s was not raised.',identifier);
end
