function report = check_full_angle_trim_point_schema()
%CHECK_FULL_ANGLE_TRIM_POINT_SCHEMA Verify atomic trim point evidence schema.

rootDir = fileparts(fileparts(mfilename('fullpath')));
addpath(rootDir);
addpath(fullfile(rootDir, 'analysis'));
addpath(fullfile(rootDir, 'model'));

outDir = tempname;
spec = struct('outputDir', outDir, 'caseName', 'schema_test', ...
    'modelType', 'legacy', 'betaM_deg', 0, 'V_mps', 12, ...
    'mode', 'helicopter_longitudinal');
result = run_full_angle_trim_point(spec);
required = {'schemaVersion','inputHash','codeCommit','modelType', ...
    'caseName','mode','definitionName','betaM_deg','V_mps', ...
    'seedSource','initialValues','unknownNames','residualNames', ...
    'fixedStates','fixedControls','runtime_s','actuallyExecuted', ...
    'converged','solverConverged','status','residualNorm', ...
    'fullResidualNorm','exitflag','theta_deg','collective_deg', ...
    'cyclicLong_deg','elevator_deg','finiteReal','atLimit', ...
    'withinLimits','wingFz_N','wingMy_Nm','branchWeight', ...
    'maxLocalRe','maxLocalMach','anyOutOfRangeClamped', ...
    'wakeCoverageMin','wakeCoverageMax','databaseSourceClasses'};
for i = 1:numel(required)
    assert(isfield(result, required{i}), 'Missing schema field %s.', required{i});
end
assert(result.actuallyExecuted && result.runtime_s > 0);
assert(~strcmp(result.status, 'NOT_RUN_AUTONOMOUS_TRIM_TIMEOUT'));
assert(exist(fullfile(outDir, 'points', 'beta000_V012_legacy.mat'), 'file') == 2);
assert(exist(fullfile(outDir, 'points', 'beta000_V012_legacy.csv'), 'file') == 2);
assert(exist(fullfile(outDir, 'points', 'beta000_V012_legacy.json'), 'file') == 2);
report.result = result;
report.allPassed = true;
fprintf('Full-angle trim point schema check: status=%s runtime=%.3fs\n', ...
    result.status, result.runtime_s);
end
