function report = check_rotor_physical_convergence()
%CHECK_ROTOR_PHYSICAL_CONVERGENCE Separate numerical and physical closure.

P = params_nominal();
d2r = pi/180;
cases = struct('name',{},'passed',{},'message',{});
x9 = zeros(9,1);
cg = zeros(3,1);

ctrl4 = struct('collective',4*d2r,'cyclicLong',0);
[~,~,rot4] = rotor_model_bemt(x9,ctrl4,0,-1,cg,P);
add_case('4 deg numerical sequence is not physical closure', ...
    rot4.coupledConverged && rot4.numericalConverged && ...
    rot4.inducedSequenceConverged && ...
    rot4.flapConverged && rot4.positiveThrustGuardActive && ...
    ~rot4.physicalBranchSupported && ...
    ~rot4.closureResidualSatisfied && ~rot4.physicalConverged && ...
    strcmp(rot4.physicalStatus, ...
    'UNSUPPORTED_NEGATIVE_THRUST_BRANCH') && ...
    isfinite(rot4.inducedClosureResidual) && ...
    abs(rot4.inducedClosureResidual) > 100, ...
    'The unsupported 4 deg branch was accepted or its residual was hidden.');

ctrl12 = struct('collective',12*d2r,'cyclicLong',0);
[~,~,rot12] = rotor_model_bemt(x9,ctrl12,0,-1,cg,P);
add_case('12 deg positive-thrust regression remains physical', ...
    rot12.coupledConverged && rot12.numericalConverged && ...
    rot12.inducedSequenceConverged && ...
    rot12.flapConverged && ~rot12.positiveThrustGuardActive && ...
    rot12.physicalBranchSupported && ...
    rot12.closureResidualSatisfied && rot12.physicalConverged && ...
    strcmp(rot12.physicalStatus,'PHYSICAL_CONVERGED') && ...
    abs(rot12.thrust-16532.1799049533) < 1e-6 && ...
    abs(rot12.torque-5000.59659267047) < 1e-6 && ...
    abs(rot12.inducedVelocity-12.1956488559134) < 1e-9, ...
    'The normal positive-thrust regression or physical status changed.');

u4 = [4*d2r;zeros(6,1)];
[~,~,fm4] = total_forces_moments(x9,u4,0,P);
[~,eom4] = tiltrotor_eom(x9,u4,0,P);
add_case('unsupported branch propagates through nine-state loads', ...
    ~fm4.physicalConverged && ~fm4.physicalBranchSupported && ...
    strcmp(fm4.physicalStatus, ...
    'UNSUPPORTED_NEGATIVE_THRUST_BRANCH') && ...
    ~eom4.physicalConverged && ...
    strcmp(eom4.physicalStatus,fm4.physicalStatus), ...
    'Nine-state force/EOM output lost the rotor physical status.');

condition = struct('V',0,'betaM',0,'gamma',0);
definition = make_trim_definition( ...
    'helicopter_longitudinal',condition,P);
[~,~,~,~,~,trimPointOut] = evaluate_trim_definition_point( ...
    condition,definition,[0;4*d2r;0],P);
add_case('trim point exposes unsupported physical branch', ...
    ~trimPointOut.physicalConverged && ...
    strcmp(trimPointOut.physicalStatus, ...
    'UNSUPPORTED_NEGATIVE_THRUST_BRANCH'), ...
    'Trim point evaluation did not expose component invalidity.');

Punsupported = P;
Punsupported.control.collectiveLim = [3.9,4.1]*d2r;
config = struct('V',0,'betaMDeg',0,'gammaDeg',0, ...
    'initialThetaDeg',0,'initialCollectiveDeg',4, ...
    'initialCyclicLongDeg',0,'thetaLimitDeg',35, ...
    'useMultiStart',false,'alwaysMultiStart',false);
serviceResult = run_trim_case(config,Punsupported);
add_case('GUI service cannot accept unsupported branch', ...
    ~serviceResult.success && ~serviceResult.physicalConverged && ...
    ~serviceResult.report.converged && ...
    strcmp(serviceResult.physicalStatus, ...
    'UNSUPPORTED_NEGATIVE_THRUST_BRANCH'), ...
    'The trim service accepted an unsupported negative-thrust point.');

x13 = [x9;0;0;0;0];
u10 = [4*d2r;zeros(9,1)];
[~,~,fm13] = total_forces_moments_13x10( ...
    x13,u10,params_berger13());
add_case('unsupported branch propagates through thirteen-state loads', ...
    ~fm13.physicalConverged && ...
    strcmp(fm13.physicalStatus, ...
    'UNSUPPORTED_NEGATIVE_THRUST_BRANCH'), ...
    'Thirteen-state force output lost the rotor physical status.');

report.cases = cases;
report.allPassed = all([cases.passed]);
report.negativePoint = rot4;
report.positivePoint = rot12;

fprintf('\nRotor physical-convergence checks\n');
fprintf('=================================\n');
for k = 1:numel(cases)
    fprintf('%-56s : %s\n',cases(k).name, ...
        ternary(cases(k).passed,'PASS','FAIL'));
    if ~cases(k).passed
        fprintf('  %s\n',cases(k).message);
    end
end
fprintf(['4 deg: T=%.9g N closure=%.9g N numerical=%d ' ...
    'physical=%d status=%s\n'],rot4.thrust, ...
    rot4.inducedClosureResidual,rot4.coupledConverged, ...
    rot4.physicalConverged,rot4.physicalStatus);
fprintf(['12 deg: T=%.9g N closure=%.9g N numerical=%d ' ...
    'physical=%d status=%s\n'],rot12.thrust, ...
    rot12.inducedClosureResidual,rot12.coupledConverged, ...
    rot12.physicalConverged,rot12.physicalStatus);

    function add_case(name,passed,message)
        cases(end+1,1) = struct('name',name, ...
            'passed',logical(passed), ...
            'message',ternary(passed,'',message));
    end
end

function value = ternary(condition,a,b)
if condition
    value = a;
else
    value = b;
end
end
