function summary = check_naca_tn_626_simple_rotor_instance()
%CHECK_NACA_TN_626_SIMPLE_ROTOR_INSTANCE Frozen mapping contract checks.
% These checks do not compare against the rotor performance targets.

P0 = params_nominal();
[P, mapping] = build_naca_tn_626_hover_validation_instance(P0, 6);

assert(abs(P.rotor.R-0.762) < 1e-12, ...
    'TN 626 radius conversion is incorrect.');
assert(P.rotor.Nb == 4, 'TN 626 blade-count mapping is incorrect.');
assert(abs(P.rotor.chord-0.0508) < 1e-12, ...
    'TN 626 chord conversion is incorrect.');
assert(abs(P.rotor.rootCut-1/6) < 1e-12, ...
    'TN 626 aerodynamic root-cut reduction is incorrect.');
assert(P.rotor.twistTip == 0, ...
    'TN 626 untwisted-blade mapping is incorrect.');
assert(abs(P.rotor.Omega-960*2*pi/60) < 1e-12, ...
    'TN 626 average RPM conversion is incorrect.');
assert(abs(mapping.collective.modelCollective_rad-6*pi/180) < 1e-12, ...
    'TN 626 incidence-to-collective conversion is incorrect.');

expectedCLmax = mean([0.906, 0.948, 0.955, 0.910]);
expectedKCD = 0.75/5.75^2;
assert(abs(P.rotor.liftSlope-5.75) < 1e-12, ...
    'TN 626 lift-slope mapping is incorrect.');
assert(abs(P.rotor.CLmax-expectedCLmax) < 1e-12, ...
    'TN 626 symmetric peak-CL reduction is incorrect.');
assert(abs(P.rotor.CD0-0.0113) < 1e-12, ...
    'TN 626 minimum-drag mapping is incorrect.');
assert(abs(P.rotor.kCD-expectedKCD) < 1e-12, ...
    'TN 626 drag-law conversion is incorrect.');
assert(P.rotor.enableCompressibilityCorrection == false, ...
    'Compressibility must remain disabled for this frozen case.');

assert(abs(P.rotor.Ib-P.rotor.bladeMass*P.rotor.R^2/3) < 1e-12, ...
    'Placeholder blade inertia was not rederived for the mapped radius.');
assert(abs(P.rotor.Sblade-P.rotor.bladeMass*P.rotor.R/2) < 1e-12, ...
    'Placeholder blade first mass moment was not rederived for radius.');
assert(mapping.readiness.readyForSimpleComparison, ...
    'Frozen TN 626 mapping was not marked ready.');
assert(~mapping.readiness.targetsUsedInMapping, ...
    'Performance targets must not enter the instance builder.');
assert(mapping.coefficientConversion.reportToStandardFactor == 0.5, ...
    'TN 626 coefficient-definition conversion is incorrect.');
assert(mapping.initialization.aircraftMass_kg == P0.mass.m, ...
    'Generic mass used for the numerical initial guess was not disclosed.');
assert(mapping.numerics.nRadial == P0.rotor.nRadial && ...
    mapping.numerics.nAzimuth == P0.rotor.nAzimuth, ...
    'The frozen validation must retain the production discretization.');

summary = struct();
summary.allPassed = true;
summary.freezeId = mapping.freezeId;
summary.claimBoundary = mapping.claimBoundary;
summary.targetsUsedInMapping = mapping.readiness.targetsUsedInMapping;
end
