function report = check_generic_trim_pr5b()
%CHECK_GENERIC_TRIM_PR5B Focused frozen-design and invariant checks.

report.cases=struct('name',{},'passed',{},'message',{});
P0=params_berger13(); [P1,m1]=params_generic_geometry_optimized();
[P2,m2]=params_generic_trim_optimized();

R1=P1; R1.base.wing.xAC=P0.base.wing.xAC;
R1.base.rotor.pivotZ=P0.base.rotor.pivotZ;
R1.base.htail.incidence=P0.base.htail.incidence;
add_case('C1 changes manifest fields only',isequaln(R1,P0), ...
    'C1 changed a non-manifest field.');

R2=P2; R2.base.wing.xAC=P0.base.wing.xAC;
R2.base.rotor.pivotZ=P0.base.rotor.pivotZ;
R2.base.htail.incidence=P0.base.htail.incidence;
R2.base.htail.CLelevator=P0.base.htail.CLelevator;
add_case('C2 changes manifest fields only',isequaln(R2,P0), ...
    'C2 changed a non-manifest field.');
add_case('default parameter function unchanged', ...
    isequaln(P0,params_berger13()) && isequaln(P0.base,params_nominal()), ...
    'An optimized parameter set leaked into the defaults.');
add_case('inertia controls and numerics invariant', ...
    isequaln(P2.base.mass,P0.base.mass) && ...
    isequaln(P2.base.control,P0.base.control) && ...
    isequaln(P2.base.trim,P0.base.trim) && ...
    isequaln(P2.base.linear,P0.base.linear), ...
    'A protected mass/control/numerical field changed.');

B=generic_trim_parameter_bounds();
values=[P2.base.wing.xAC;P2.base.rotor.pivotZ; ...
    P2.base.htail.incidence;P2.base.htail.CLelevator];
add_case('frozen values remain inside declared bounds', ...
    all(values>=B.lower(1:4)) && all(values<=B.upper(1:4)), ...
    'A frozen parameter is outside its declared bound.');
add_case('one effective parameter only', ...
    sum(strcmp({m2.records.claimClass},'CALIBRATED_EFFECTIVE'))==1 && ...
    numel(m1.records)==3 && numel(m2.records)==4, ...
    'Formal C2 contains an unexpected effective parameter.');

G=generic_trim_dense_validation_grid();
add_case('dense grid includes frozen required stations', ...
    all(ismember([0 30 60 90],unique(G.betaDeg).')) && height(G)==13, ...
    'Dense validation grid does not contain the required beta stations.');
add_case('robustness perturbations stay inside bounds', ...
    0.08>=B.lower(1) && 0.12<=B.upper(1) && ...
    0.08>=B.lower(2) && 0.12<=B.upper(2) && ...
    -5>=B.lower(3)*180/pi && -4.5<=B.upper(3)*180/pi && ...
    2.30>=B.lower(4) && 2.40<=B.upper(4), ...
    'Post-freeze perturbation set exceeds a declared bound.');

S=table({'CREDIBLE';'FAILED'},[1e-9;2],[50;100], ...
    [20;20],[0;0],[-10;-20], ...
    'VariableNames',{'status','dynamicResidualNorm','conditionNumber', ...
    'collectiveDeg','cyclicLongDeg','elevatorDeg'});
[J1,t1]=generic_trim_objective(S,P2); [J2,t2]=generic_trim_objective(S,P2);
add_case('objective is finite and reproducible', ...
    isfinite(J1) && isequaln(J1,J2) && isequaln(t1,t2) && t1.external==0, ...
    'Objective is non-finite, non-reproducible, or uses holdout data.');

rootDir=fileparts(fileparts(mfilename('fullpath')));
deliverables=fullfile(rootDir,'results','generic_trim_pr5b','deliverables');
requiredFiles={ ...
    'MODEL_C1_GEOMETRY_OPTIMIZED_RESULTS.csv'; ...
    'MODEL_C2_EFFECTIVE_OPTIMIZED_RESULTS.csv'; ...
    'DENSE_TRIM_CORRIDOR.csv';'CONTROL_MARGIN_RESULTS.csv'; ...
    'EXTERNAL_CALIBRATION_SET.csv';'EXTERNAL_VALIDATION_SET.csv'; ...
    'PARAMETER_ROBUSTNESS_RESULTS.csv'};
add_case('required frozen evidence is present', ...
    all(cellfun(@(f) exist(fullfile(deliverables,f),'file')==2,requiredFiles)), ...
    'One or more PR5B frozen-evidence files are absent.');

if all(cellfun(@(f) exist(fullfile(deliverables,f),'file')==2,requiredFiles))
    C1=readtable(fullfile(deliverables,requiredFiles{1}));
    C2=readtable(fullfile(deliverables,requiredFiles{2}));
    add_case('formal design anchors retain failures', ...
        height(C1)==9 && height(C2)==9 && ...
        sum(strcmp(C1.status,'CREDIBLE'))==8 && ...
        sum(strcmp(C2.status,'CREDIBLE'))==8 && ...
        strcmp(C2.status{strcmp(C2.pointId,'B75_V040')},'FAILED') && ...
        all(as_logical(C1.finiteReal)) && all(as_logical(C2.finiteReal)), ...
        'Formal C1/C2 anchor evidence changed or hid a failure.');

    CM=readtable(fullfile(deliverables,requiredFiles{4}));
    q=strcmp(CM.variant,'Model C2') & strcmp(CM.pointId,'B75_V060');
    add_case('key C2 control margin passes 10 percent', ...
        sum(q)==1 && as_logical(CM.passes10Percent(q)) && ...
        CM.elevatorMarginFraction(q)>=0.10, ...
        'B75/V60 does not retain the frozen 10% control-margin result.');

    D=readtable(fullfile(deliverables,requiredFiles{3}));
    extra=strcmp(D.setClass,'POST_FREEZE_DENSE_EXTRA');
    add_case('dense corridor is finite with explicit gaps', ...
        sum(extra)==13 && all(as_logical(D.finiteReal(extra))) && ...
        sum(strcmp(D.status(extra),'CREDIBLE'))==10 && ...
        sum(strcmp(D.status(extra),'FAILED'))==3, ...
        'Dense corridor count, finite-real gate, or explicit gaps changed.');

    Cal=readtable(fullfile(deliverables,requiredFiles{5}));
    Val=readtable(fullfile(deliverables,requiredFiles{6}));
    add_case('calibration and validation sets remain isolated', ...
        isempty(intersect(Cal.recordId,Val.recordId)) && ...
        height(Val)/(height(Cal)+height(Val))>=0.30 && ...
        ~any(as_logical(Cal.usedInObjective)) && ...
        ~any(as_logical(Val.usedInObjective)), ...
        'Holdout split overlaps, is too small, or leaked into the objective.');

    R=readtable(fullfile(deliverables,requiredFiles{7}));
    scenarios=unique(R.scenario);
    stablePattern=true;
    for k=1:numel(scenarios)
        stablePattern=stablePattern && ...
            sum(as_logical(R.credible(strcmp(R.scenario,scenarios{k}))))==2;
    end
    add_case('post-freeze perturbation pattern is retained', ...
        height(R)==21 && all(as_logical(R.finiteReal)) && stablePattern, ...
        'Robustness set changed, became non-finite, or fed back into tuning.');
end

x13=[40;0;1;zeros(6,1);45*pi/180;45*pi/180;0;0];
u10=[18;0;0;0;0;0;-5;0;0;0]*pi/180;
[F13,M13,info13]=total_forces_moments_13x10(x13,u10,P0);
add_case('13x10 optimized-branch regression is finite', ...
    all(isfinite([F13(:);M13(:)])) && isreal([F13(:);M13(:)]) && ...
    isfield(info13,'components'), ...
    'The unchanged 13x10 path is non-finite or structurally incomplete.');

report.allPassed=all([report.cases.passed]);
fprintf('\nPR5B generic trim checks\n========================\n');
for k=1:numel(report.cases)
    if report.cases(k).passed, status='PASS'; else, status='FAIL'; end
    fprintf('%-42s : %s\n',report.cases(k).name,status);
end
fprintf('All PR5B checks passed: %d\n',report.allPassed);

    function add_case(name,passed,message)
        report.cases(end+1,1)=struct('name',name,'passed',logical(passed), ...
            'message',ternary(passed,'',message));
    end
end

function value=ternary(condition,a,b)
if condition, value=a; else, value=b; end
end

function value=as_logical(raw)
if islogical(raw)
    value=raw;
elseif isnumeric(raw)
    value=raw~=0;
elseif iscell(raw)
    value=strcmpi(raw,'true') | strcmp(raw,'1');
else
    value=strcmpi(cellstr(raw),'true') | strcmp(cellstr(raw),'1');
end
end
