function report = check_nuaa_source_freeze_scaffold()
%CHECK_NUAA_SOURCE_FREEZE_SCAFFOLD Lightweight NUAA scaffold checks.

rootDir = fileparts(fileparts(mfilename('fullpath')));
sourceReadmePath = fullfile(rootDir, 'validation', ...
    'external_sources', 'nuaa', 'README.md');
dataReadmePath = fullfile(rootDir, 'validation', ...
    'external_digitized_data', 'nuaa', 'README.md');
templateDir = fullfile(rootDir, 'validation', ...
    'external_digitized_data', 'nuaa', 'templates');
provenancePath = fullfile(rootDir, 'validation', ...
    'external_digitized_data', 'nuaa', 'provenance', ...
    'nuaa_fig5_fig6_provenance_template.md');

templateFiles = { ...
    'nuaa_fig5a_helicopter_trim_template.csv', ...
    'nuaa_fig5b_airplane_trim_template.csv', ...
    'nuaa_fig6a_transition_15deg_trim_template.csv', ...
    'nuaa_fig6b_transition_75deg_trim_template.csv'};

cases = {};
passed = [];
messages = {};

run_case('required scaffold files exist', @check_files_exist);
run_case('CSV templates expose required headers', @check_csv_headers);
run_case('README and provenance preserve audit boundaries', ...
    @check_boundary_terms);
run_case('scaffold avoids forbidden claims', @check_forbidden_claims);

report.names = cases;
report.passed = passed;
report.messages = messages;
report.allPassed = all(passed);

fprintf('\nNUAA source-freeze scaffold checks\n');
fprintf('==================================\n');
for displayIdx = 1:numel(cases)
    fprintf('%-56s : %s\n', cases{displayIdx}, ...
        ternary(passed(displayIdx), 'PASS', 'FAIL'));
    if ~passed(displayIdx)
        fprintf('  %s\n', messages{displayIdx});
    end
end
fprintf('All passed: %d\n', report.allPassed);

    function run_case(name, fun)
        cases{end+1,1} = name;
        try
            fun();
            passed(end+1,1) = true;
            messages{end+1,1} = '';
        catch ME
            passed(end+1,1) = false;
            messages{end+1,1} = ME.message;
        end
    end

    function check_files_exist()
        assert(isfile(sourceReadmePath), ...
            'validation/external_sources/nuaa/README.md is missing.');
        assert(isfile(dataReadmePath), ...
            'validation/external_digitized_data/nuaa/README.md is missing.');
        assert(isfile(provenancePath), ...
            'NUAA provenance template is missing.');
        for fileIdx = 1:numel(templateFiles)
            assert(isfile(fullfile(templateDir, templateFiles{fileIdx})), ...
                'Missing CSV template: %s', templateFiles{fileIdx});
        end
    end

    function check_csv_headers()
        requiredHeaders = { ...
            'source_id', ...
            'figure', ...
            'subplot', ...
            'betam_deg', ...
            'airspeed_mps', ...
            'external_variable', ...
            'external_value', ...
            'external_unit', ...
            'sign_convention_status', ...
            'unit_conversion_status'};
        for fileIdx = 1:numel(templateFiles)
            text = lower(fileread(fullfile(templateDir, ...
                templateFiles{fileIdx})));
            for headerIdx = 1:numel(requiredHeaders)
                assert(contains(text, requiredHeaders{headerIdx}), ...
                    'Missing header %s in %s.', ...
                    requiredHeaders{headerIdx}, templateFiles{fileIdx});
            end
        end
    end

    function check_boundary_terms()
        text = lower([fileread(sourceReadmePath), newline, ...
            fileread(dataReadmePath), newline, fileread(provenancePath)]);
        requiredTerms = { ...
            'source_required', ...
            'sign_convention_required', ...
            'not validation', ...
            'no guessed values', ...
            'no pass/fail labels'};
        for termIdx = 1:numel(requiredTerms)
            assert(contains(text, requiredTerms{termIdx}), ...
                'Missing boundary term: %s', requiredTerms{termIdx});
        end
    end

    function check_forbidden_claims()
        text = lower([fileread(sourceReadmePath), newline, ...
            fileread(dataReadmePath), newline, fileread(provenancePath)]);
        forbidden = { ...
            'validation completed', ...
            'trend match passed', ...
            'reproduced fig.5', ...
            'reproduced fig.6', ...
            'xv-15 validation completed', ...
            'nuaa validation completed'};
        for forbiddenIdx = 1:numel(forbidden)
            assert(~contains(text, forbidden{forbiddenIdx}), ...
                'Forbidden claim found: %s', forbidden{forbiddenIdx});
        end
    end

    function value = ternary(condition, a, b)
        if condition
            value = a;
        else
            value = b;
        end
    end
end
