function contract = berger13_derivative_contract()
%BERGER13_DERIVATIVE_CONTRACT Explicit names/units for command Jacobians.

contract.stateNames = {'u';'v';'w';'p';'q';'r';'phi';'theta';'psi'; ...
    'betaSym';'betaDiff';'betaSymDot';'betaDiffDot'};
contract.stateUnits = {'m/s';'m/s';'m/s';'rad/s';'rad/s';'rad/s'; ...
    'rad';'rad';'rad';'rad';'rad';'rad/s';'rad/s'};
contract.stateDerivativeNames = {'udot';'vdot';'wdot';'pdot';'qdot'; ...
    'rdot';'phidot';'thetadot';'psidot';'betaSymDot';'betaDiffDot'; ...
    'betaSymDDot';'betaDiffDDot'};
contract.stateDerivativeUnits = {'m/s^2';'m/s^2';'m/s^2'; ...
    'rad/s^2';'rad/s^2';'rad/s^2';'rad/s';'rad/s';'rad/s'; ...
    'rad/s';'rad/s';'rad/s^2';'rad/s^2'};
contract.commandInputNames = {'collective';'diffCollective'; ...
    'cyclicLong';'diffCyclic';'lateralCyclic';'aileron';'elevator'; ...
    'rudder';'betaSymCommand';'betaDiffCommand'};
contract.commandInputUnits = repmat({'rad'},10,1);
contract.parameterSource = 'DEFINITIONAL_UNIT_CONTRACT';
end
