function catalog = build_parameter_catalog()
%BUILD_PARAMETER_CATALOG Build metadata for editable GUI parameters.

catalog = repmat(empty_item(), 0, 1);

catalog = add(catalog, 'env.rho', '环境', '空气密度', ...
    '标准大气密度，参与动压、旋翼诱导速度和气动力计算。', '环境设定', ...
    'kg/m^3', 'kg/m^3', {'env','rho'}, [], 'scalar', ...
    1, 0, 0, Inf, false, true, false, 'direct', 'environment');
catalog = add(catalog, 'env.g', '环境', '重力加速度', ...
    '重力加速度，参与重量、配平尺度和刚体运动方程。', '环境设定', ...
    'm/s^2', 'm/s^2', {'env','g'}, [], 'scalar', ...
    1, 0, 0, Inf, false, true, false, 'direct', 'environment');

catalog = add(catalog, 'mass.m', '整机质量与惯量', '总质量', ...
    '整机总质量，用于平动和转动动力学。', '质量与惯量设定', ...
    'kg', 'kg', {'mass','m'}, [], 'scalar', ...
    1, 0, 0, Inf, false, true, false, 'direct', 'mass');
catalog = add(catalog, 'mass.mNac', '倾转机构', '左右短舱和旋翼组件总质量', ...
    '左右倾转组件合计移动质量，用于短舱倾转导致的重心偏移。', '质量与惯量设定', ...
    'kg', 'kg', {'mass','mNac'}, [], 'scalar', ...
    1, 0, 0, Inf, true, true, false, 'direct', 'mass');
catalog = add(catalog, 'mass.RH_mass', '倾转机构', '倾转组件重心到转轴的距离', ...
    '移动质量质心到倾转轴的等效距离，用于计算短舱倾转重心偏移。', '质量与惯量设定', ...
    'm', 'm', {'mass','RH_mass'}, [], 'scalar', ...
    1, 0, 0, Inf, true, true, false, 'direct', 'mass');

catalog = add_inertia(catalog, 'mass.I0.Ixx', 'Ixx', [1 1]);
catalog = add_inertia(catalog, 'mass.I0.Iyy', 'Iyy', [2 2]);
catalog = add_inertia(catalog, 'mass.I0.Izz', 'Izz', [3 3]);
catalog = add_inertia(catalog, 'mass.I0.Ixy', 'Ixy', [1 2]);
catalog = add_inertia(catalog, 'mass.I0.Ixz', 'Ixz', [1 3]);
catalog = add_inertia(catalog, 'mass.I0.Iyz', 'Iyz', [2 3]);
catalog = add_ki(catalog, 'mass.KI.KIxx', 'KIxx', [1 1]);
catalog = add_ki(catalog, 'mass.KI.KIyy', 'KIyy', [2 2]);
catalog = add_ki(catalog, 'mass.KI.KIzz', 'KIzz', [3 3]);

catalog = add(catalog, 'rotor.R', '旋翼', '旋翼半径', ...
    '旋翼叶尖半径，影响盘面积、叶素位置和桨叶派生惯量。', '几何设定', ...
    'm', 'm', {'rotor','R'}, [], 'scalar', ...
    1, 0, 0, Inf, false, true, false, 'rotorDerived', 'rotorDerived');
catalog = add(catalog, 'rotor.Nb', '旋翼', '桨叶数', ...
    '单副旋翼的桨叶数量，影响叶素载荷合计。', '几何设定', ...
    '片', '片', {'rotor','Nb'}, [], 'integer', ...
    1, 0, 1, Inf, true, true, true, 'direct', 'rotor');
catalog = add(catalog, 'rotor.Omega', '旋翼', '旋翼角速度', ...
    '旋翼恒定角速度，影响叶素切向速度和挥舞惯性项。', '几何设定', ...
    'rad/s', 'rad/s', {'rotor','Omega'}, [], 'scalar', ...
    1, 0, 0, Inf, false, true, false, 'direct', 'rotor');
catalog = add(catalog, 'rotor.chord', '旋翼', '桨叶弦长', ...
    '叶素气动力使用的等效桨叶弦长。', '几何设定', ...
    'm', 'm', {'rotor','chord'}, [], 'scalar', ...
    1, 0, 0, Inf, false, true, false, 'direct', 'rotor');
catalog = add(catalog, 'rotor.rootCut', '旋翼几何', '叶素计算起始位置（占旋翼半径）', ...
    '叶素积分起点占旋翼半径的比例。', '几何设定', ...
    '无量纲', '无量纲', {'rotor','rootCut'}, [], 'scalar', ...
    1, 0, 0, 1, true, false, false, 'direct', 'rotor');
catalog = add(catalog, 'rotor.twistTip', '旋翼几何', '桨叶总扭转角（根部至桨尖）', ...
    '桨尖相对根部积分起点的线性扭转角。', '几何设定', ...
    'deg', 'rad', {'rotor','twistTip'}, [], 'scalar', ...
    180/pi, 0, -90, 90, true, true, false, 'direct', 'rotor');

catalog = add(catalog, 'rotor.liftSlope', '旋翼', '桨叶升力线斜率', ...
    '桨叶截面升力随迎角变化的模型系数。', '气动模型设定', ...
    '1/rad', '1/rad', {'rotor','liftSlope'}, [], 'scalar', ...
    1, 0, -1e4, 1e4, true, true, false, 'direct', 'rotor');
catalog = add(catalog, 'rotor.CLmax', '旋翼', '桨叶最大升力系数', ...
    '桨叶升力系数饱和尺度。', '气动模型设定', ...
    '无量纲', '无量纲', {'rotor','CLmax'}, [], 'scalar', ...
    1, 0, 0, Inf, false, true, false, 'direct', 'rotor');
catalog = add(catalog, 'rotor.CD0', '旋翼', '桨叶零升阻力系数', ...
    '桨叶剖面阻力的基值。', '气动模型设定', ...
    '无量纲', '无量纲', {'rotor','CD0'}, [], 'scalar', ...
    1, 0, 0, Inf, true, true, false, 'direct', 'rotor');
catalog = add(catalog, 'rotor.kCD', '旋翼', '桨叶阻力二次项系数', ...
    '桨叶阻力随升力系数平方变化的系数。', '气动模型设定', ...
    '无量纲', '无量纲', {'rotor','kCD'}, [], 'scalar', ...
    1, 0, 0, Inf, true, true, false, 'direct', 'rotor');

catalog = add(catalog, 'rotor.pivotX', '倾转机构', '短舱转轴前后位置', ...
    '旋翼短舱转轴在机体系纵向的位置。', '几何设定', ...
    'm', 'm', {'rotor','pivotX'}, [], 'scalar', ...
    1, 0, -Inf, Inf, true, true, false, 'direct', 'rotor');
catalog = add(catalog, 'rotor.pivotY', '倾转机构', '短舱转轴到机身中心线的距离', ...
    '单侧旋翼短舱转轴相对机体对称面的横向距离。', '几何设定', ...
    'm', 'm', {'rotor','pivotY'}, [], 'scalar', ...
    1, 0, 0, Inf, false, true, false, 'direct', 'rotor');
catalog = add(catalog, 'rotor.pivotZ', '倾转机构', '短舱转轴上下位置', ...
    '旋翼短舱转轴在机体系垂向的位置。', '几何设定', ...
    'm', 'm', {'rotor','pivotZ'}, [], 'scalar', ...
    1, 0, -Inf, Inf, true, true, false, 'direct', 'rotor');
catalog = add(catalog, 'rotor.RH_hub', '倾转机构', '桨毂到短舱转轴的距离', ...
    '桨毂相对短舱倾转轴的等效距离。', '几何设定', ...
    'm', 'm', {'rotor','RH_hub'}, [], 'scalar', ...
    1, 0, 0, Inf, true, true, false, 'direct', 'rotor');

catalog = add(catalog, 'rotor.nRadial', '旋翼', '径向离散数', ...
    '叶素积分使用的径向分段数量。', '计算精度设置', ...
    '段', '段', {'rotor','nRadial'}, [], 'integer', ...
    1, 0, 2, Inf, true, true, true, 'direct', 'rotorGrid');
catalog = add(catalog, 'rotor.nAzimuth', '旋翼', '方位离散数', ...
    '叶素积分使用的方位采样数量。', '计算精度设置', ...
    '点', '点', {'rotor','nAzimuth'}, [], 'integer', ...
    1, 0, 4, Inf, true, true, true, 'direct', 'rotorGrid');
catalog = add(catalog, 'rotor.inducedMaxIter', '旋翼', '诱导速度最大迭代次数', ...
    '旋翼诱导速度和挥舞耦合求解的外层最大迭代次数。', '计算精度设置', ...
    '次', '次', {'rotor','inducedMaxIter'}, [], 'integer', ...
    1, 0, 1, Inf, true, true, true, 'direct', 'rotorSolve');
catalog = add(catalog, 'rotor.inducedRelax', '旋翼', '诱导速度松弛因子', ...
    '诱导速度迭代更新的松弛比例。', '计算精度设置', ...
    '无量纲', '无量纲', {'rotor','inducedRelax'}, [], 'scalar', ...
    1, 0, 0, 1, false, true, false, 'direct', 'rotorSolve');
catalog = add(catalog, 'rotor.inducedTol', '旋翼', '诱导速度收敛容限', ...
    '诱导速度相对变化的收敛阈值。', '计算精度设置', ...
    '无量纲', '无量纲', {'rotor','inducedTol'}, [], 'scalar', ...
    1, 0, 0, Inf, false, true, false, 'direct', 'rotorSolve');
catalog = add(catalog, 'rotor.bladeMass', '旋翼', '单片桨叶质量', ...
    '用于派生桨叶挥舞惯量和一阶质量矩的单片桨叶质量。', '质量与惯量设定', ...
    'kg', 'kg', {'rotor','bladeMass'}, [], 'scalar', ...
    1, 0, 0, Inf, false, true, false, 'rotorDerived', 'rotorDerived');
catalog = add(catalog, 'rotor.flapResidualTol', '旋翼', '挥舞残差容限', ...
    '稳态一阶挥舞求解的无量纲残差容限。', '计算精度设置', ...
    '无量纲', '无量纲', {'rotor','flapResidualTol'}, [], 'scalar', ...
    1, 0, 0, Inf, false, true, false, 'direct', 'flapSolve');
catalog = add(catalog, 'rotor.flapMaxIter', '旋翼', '挥舞最大迭代次数', ...
    '挥舞方程牛顿求解的最大迭代次数。', '计算精度设置', ...
    '次', '次', {'rotor','flapMaxIter'}, [], 'integer', ...
    1, 0, 1, Inf, true, true, true, 'direct', 'flapSolve');
catalog = add(catalog, 'rotor.flapJacobianStep', '旋翼', '挥舞雅可比差分步长', ...
    '挥舞残差数值雅可比的相对扰动步长。', '计算精度设置', ...
    '无量纲', '无量纲', {'rotor','flapJacobianStep'}, [], 'scalar', ...
    1, 0, 0, Inf, false, true, false, 'direct', 'flapSolve');
catalog = add(catalog, 'rotor.flapNewtonDamping', '旋翼', '挥舞线搜索阻尼因子', ...
    '挥舞牛顿步线搜索使用的步长缩减比例。', '计算精度设置', ...
    '无量纲', '无量纲', {'rotor','flapNewtonDamping'}, [], 'scalar', ...
    1, 0, 0, 1, false, true, false, 'direct', 'flapSolve');
catalog = add(catalog, 'rotor.flapNewtonRegularization', '旋翼', '挥舞牛顿正则化量', ...
    '挥舞最小二乘牛顿修正中的正则化量。', '计算精度设置', ...
    '无量纲', '无量纲', {'rotor','flapNewtonRegularization'}, [], 'scalar', ...
    1, 0, 0, Inf, false, true, false, 'direct', 'flapSolve');
catalog = add(catalog, 'rotor.flapLineSearchMaxIter', '旋翼', '挥舞线搜索最大次数', ...
    '挥舞线搜索允许的最大试探次数。', '计算精度设置', ...
    '次', '次', {'rotor','flapLineSearchMaxIter'}, [], 'integer', ...
    1, 0, 1, Inf, true, true, true, 'direct', 'flapSolve');
catalog = add(catalog, 'rotor.flapDivergenceAngle', '旋翼', '挥舞发散角限值', ...
    '挥舞求解中判定姿态过大的角度限值。', '计算精度设置', ...
    'deg', 'rad', {'rotor','flapDivergenceAngle'}, [], 'scalar', ...
    180/pi, 0, 0, 90, false, true, false, 'direct', 'flapSolve');
catalog = add(catalog, 'rotor.wakeFactor', '旋翼', '旋翼尾流速度系数', ...
    '旋翼诱导速度作用到机翼滑流区域的放大系数。', '气动模型设定', ...
    '无量纲', '无量纲', {'rotor','wakeFactor'}, [], 'scalar', ...
    1, 0, 0, Inf, true, true, false, 'direct', 'rotorWake');
catalog = add(catalog, 'rotor.Jpolar', '旋翼几何', '旋翼自转惯量', ...
    '可选旋翼陀螺项使用的转动极惯量。', '质量与惯量设定', ...
    'kg m^2', 'kg m^2', {'rotor','Jpolar'}, [], 'scalar', ...
    1, 0, 0, Inf, true, true, false, 'direct', 'rotor');

catalog = add_wing(catalog);
catalog = add_fuselage(catalog);
catalog = add_htail(catalog);
catalog = add_vtail(catalog);
catalog = add_controls(catalog);
catalog = add_trim(catalog);
catalog = add_linear(catalog);
catalog = normalize_catalog_categories(catalog);
end

function item = empty_item()
item = struct('id', '', 'category', '', 'name', '', 'description', '', ...
    'basis', '', 'displayUnit', '', 'internalUnit', '', ...
    'path', {{}}, 'subscript', [], 'valueType', '', 'displayScale', 1, ...
    'displayOffset', 0, 'minimum', -Inf, 'maximum', Inf, ...
    'minimumInclusive', true, 'maximumInclusive', true, ...
    'integerRequired', false, 'writePolicy', '', 'dependencyGroup', '');
end

function catalog = add(catalog, id, category, name, description, basis, ...
    displayUnit, internalUnit, path, subscript, valueType, displayScale, ...
    displayOffset, minimum, maximum, minimumInclusive, maximumInclusive, ...
    integerRequired, writePolicy, dependencyGroup)
item = empty_item();
item.id = id;
item.category = category;
item.name = name;
item.description = description;
item.basis = basis;
item.displayUnit = displayUnit;
item.internalUnit = internalUnit;
item.path = path;
item.subscript = subscript;
item.valueType = valueType;
item.displayScale = displayScale;
item.displayOffset = displayOffset;
item.minimum = minimum;
item.maximum = maximum;
item.minimumInclusive = minimumInclusive;
item.maximumInclusive = maximumInclusive;
item.integerRequired = integerRequired;
item.writePolicy = writePolicy;
item.dependencyGroup = dependencyGroup;
catalog(end+1,1) = item;
end

function catalog = add_inertia(catalog, id, name, subscript)
catalog = add(catalog, id, '整机质量与惯量', inertia_name(name), ...
    ['短舱倾转角为零时的整机名义惯量矩阵分量 ' name '。'], ...
    '质量与惯量设定', 'kg m^2', 'kg m^2', {'mass','I0'}, ...
    subscript, 'scalar', 1, 0, -Inf, Inf, true, true, false, ...
    'symmetricI0', 'inertia');
end

function catalog = add_ki(catalog, id, name, subscript)
catalog = add(catalog, id, '整机质量与惯量', inertia_rate_name(name), ...
    ['当前惯量变化近似中，惯量矩阵随短舱倾转角变化的对角分量 ' name '。'], ...
    '质量与惯量设定', 'kg m^2/rad', 'kg m^2/rad', ...
    {'mass','KI'}, subscript, 'scalar', 1, 0, -Inf, Inf, true, true, ...
    false, 'diagKI', 'inertia');
end

function name = inertia_name(symbol)
switch symbol
    case 'Ixx'
        name = '滚转惯量 Ixx';
    case 'Iyy'
        name = '俯仰惯量 Iyy';
    case 'Izz'
        name = '偏航惯量 Izz';
    case 'Ixy'
        name = '滚转-俯仰耦合惯量 Ixy';
    case 'Ixz'
        name = '滚转-偏航耦合惯量 Ixz';
    case 'Iyz'
        name = '俯仰-偏航耦合惯量 Iyz';
    otherwise
        name = symbol;
end
end

function name = inertia_rate_name(symbol)
switch symbol
    case 'KIxx'
        name = '滚转惯量随倾转角变化系数';
    case 'KIyy'
        name = '俯仰惯量随倾转角变化系数';
    case 'KIzz'
        name = '偏航惯量随倾转角变化系数';
    otherwise
        name = ['惯量变化系数 ' symbol];
end
end

function catalog = add_wing(catalog)
items = {
    'wing.S','机翼面积','机翼总参考面积。','几何设定','m^2','m^2',{'wing','S'},[],1,0,0,Inf,false,true,false,'direct','wing';
    'wing.c','机翼平均弦长','机翼气动力矩使用的平均弦长。','几何设定','m','m',{'wing','c'},[],1,0,0,Inf,false,true,false,'direct','wing';
    'wing.xAC','机翼气动中心纵向位置','机翼自由流和滑流区域共用的纵向气动中心。','几何设定','m','m',{'wing','xAC'},[],1,0,-Inf,Inf,true,true,false,'direct','wing';
    'wing.yFreeAC','机翼自由流区域横向位置','单侧机翼自由流区域气动中心横向距离。','几何设定','m','m',{'wing','yFreeAC'},[],1,0,0,Inf,true,true,false,'direct','wing';
    'wing.ySlipAC','机翼滑流区域横向位置','单侧机翼滑流区域气动中心横向距离。','几何设定','m','m',{'wing','ySlipAC'},[],1,0,0,Inf,true,true,false,'direct','wing';
    'wing.zAC','机翼气动中心垂向位置','机翼气动中心垂向位置。','几何设定','m','m',{'wing','zAC'},[],1,0,-Inf,Inf,true,true,false,'direct','wing';
    'wing.CL0','机翼零迎角升力系数','机翼升力模型的零迎角项。','气动模型设定','无量纲','无量纲',{'wing','CL0'},[],1,0,-1e4,1e4,true,true,false,'direct','wing';
    'wing.CLalpha','机翼升力线斜率','机翼升力随迎角变化的系数。','气动模型设定','1/rad','1/rad',{'wing','CLalpha'},[],1,0,-1e4,1e4,true,true,false,'direct','wing';
    'wing.CLmax','机翼最大升力系数','机翼升力系数饱和尺度。','气动模型设定','无量纲','无量纲',{'wing','CLmax'},[],1,0,0,Inf,false,true,false,'direct','wing';
    'wing.CD0','机翼零升阻力系数','机翼阻力模型基值。','气动模型设定','无量纲','无量纲',{'wing','CD0'},[],1,0,0,Inf,true,true,false,'direct','wing';
    'wing.kInduced','机翼诱导阻力系数','机翼阻力随升力平方变化的系数。','气动模型设定','无量纲','无量纲',{'wing','kInduced'},[],1,0,0,Inf,true,true,false,'direct','wing';
    'wing.CYbeta','侧滑对机翼侧向力的影响（CYβ）','机翼侧力随侧滑角变化的系数。','气动模型设定','1/rad','1/rad',{'wing','CYbeta'},[],1,0,-1e4,1e4,true,true,false,'direct','wing';
    'wing.Cm0','机翼零迎角俯仰力矩系数','CALIBRATED_EFFECTIVE_PARAMETER：保留机翼关于当前气动参考点的非零基础固有俯仰矩；不是 NASA、XV-15 或南航文章直接测量值。','标定有效参数','无量纲','无量纲',{'wing','Cm0'},[],1,0,-1e4,1e4,true,true,false,'direct','wing';
    'wing.Cmalpha','机翼俯仰力矩迎角导数','INITIAL_MECHANISTIC_ASSUMPTION：当前 wing.rAC 视为等效气动中心，线性附着流直接固有俯仰矩斜率暂取零；真实值未被确定为零。','初期机理假设','1/rad','1/rad',{'wing','Cmalpha'},[],1,0,-1e4,1e4,true,true,false,'direct','wing';
    'wing.CLaileron','副翼对机翼升力的影响','副翼对机翼升力系数的影响系数。','气动模型设定','1/rad','1/rad',{'wing','CLaileron'},[],1,0,-1e4,1e4,true,true,false,'direct','wing';
    'wing.Cmaileron','副翼对俯仰力矩的影响','副翼对机翼俯仰力矩系数的影响系数。','气动模型设定','1/rad','1/rad',{'wing','Cmaileron'},[],1,0,-1e4,1e4,true,true,false,'direct','wing';
    'wing.SslipMaxHalf','单侧滑流最大面积','单侧机翼可进入旋翼滑流的最大面积。','几何设定','m^2','m^2',{'wing','SslipMaxHalf'},[],1,0,0,Inf,true,true,false,'direct','wing';
    'wing.muMax','滑流面积衰减参考前进比','滑流面积随旋翼前进比减小的参考尺度。','气动模型设定','无量纲','无量纲',{'wing','muMax'},[],1,0,0,Inf,false,true,false,'direct','wing';
    'wing.CDnormal','近法向流阻力系数','机翼近法向来流分支使用的阻力系数。','气动模型设定','无量纲','无量纲',{'wing','CDnormal'},[],1,0,0,Inf,true,true,false,'direct','wing';
    'wing.normalFlowRatio','近法向混合中心','近法向分支与升力线分支的混合中心。','气动模型设定','无量纲','无量纲',{'wing','normalFlowRatio'},[],1,0,0,1,true,true,false,'direct','wing';
    'wing.normalFlowBlendHalfWidth','近法向混合半宽','近法向分支与升力线分支连续混合的半宽。','气动模型设定','无量纲','无量纲',{'wing','normalFlowBlendHalfWidth'},[],1,0,0,1,false,true,false,'direct','wing'};
catalog = add_rows(catalog, '机翼', items);
end

function catalog = add_fuselage(catalog)
items = {
    'fuselage.S','机身参考面积','机身气动力使用的参考面积。','几何设定','m^2','m^2',{'fuselage','S'},[],1,0,0,Inf,false,true,false,'direct','fuselage';
    'fuselage.b','机身横向参考长度','机身滚转和偏航力矩使用的参考长度。','几何设定','m','m',{'fuselage','b'},[],1,0,0,Inf,false,true,false,'direct','fuselage';
    'fuselage.c','机身纵向参考长度','机身俯仰力矩使用的参考长度。','几何设定','m','m',{'fuselage','c'},[],1,0,0,Inf,false,true,false,'direct','fuselage';
    'fuselage.rAC.x','机身气动中心纵向位置','机身气动力作用点的纵向位置。','几何设定','m','m',{'fuselage','rAC'},1,1,0,-Inf,Inf,true,true,false,'direct','fuselage';
    'fuselage.rAC.y','机身气动中心横向位置','机身气动力作用点的横向位置。','几何设定','m','m',{'fuselage','rAC'},2,1,0,-Inf,Inf,true,true,false,'direct','fuselage';
    'fuselage.rAC.z','机身气动中心垂向位置','机身气动力作用点的垂向位置。','几何设定','m','m',{'fuselage','rAC'},3,1,0,-Inf,Inf,true,true,false,'direct','fuselage';
    'fuselage.CD0','机身零迎角阻力系数','机身阻力模型基值。','气动模型设定','无量纲','无量纲',{'fuselage','CD0'},[],1,0,0,Inf,true,true,false,'direct','fuselage';
    'fuselage.CDalpha2','机身迎角阻力二次项','机身阻力随迎角平方变化的系数。','气动模型设定','无量纲','无量纲',{'fuselage','CDalpha2'},[],1,0,0,Inf,true,true,false,'direct','fuselage';
    'fuselage.CDbeta2','机身侧滑阻力二次项','机身阻力随侧滑角平方变化的系数。','气动模型设定','无量纲','无量纲',{'fuselage','CDbeta2'},[],1,0,0,Inf,true,true,false,'direct','fuselage';
    'fuselage.CL0','机身零迎角升力系数','机身升力模型常值项。','气动模型设定','无量纲','无量纲',{'fuselage','CL0'},[],1,0,-1e4,1e4,true,true,false,'direct','fuselage';
    'fuselage.CLalpha','机身升力迎角导数','机身升力随迎角变化的系数。','气动模型设定','1/rad','1/rad',{'fuselage','CLalpha'},[],1,0,-1e4,1e4,true,true,false,'direct','fuselage';
    'fuselage.CYbeta','侧滑对机身侧向力的影响','机身侧力随侧滑角变化的系数。','气动模型设定','1/rad','1/rad',{'fuselage','CYbeta'},[],1,0,-1e4,1e4,true,true,false,'direct','fuselage';
    'fuselage.Clbeta','侧滑对机身滚转力矩的影响','机身滚转力矩随侧滑角变化的系数。','气动模型设定','1/rad','1/rad',{'fuselage','Clbeta'},[],1,0,-1e4,1e4,true,true,false,'direct','fuselage';
    'fuselage.Clp','机身滚转阻尼导数','机身滚转力矩随滚转角速度变化的系数。','气动模型设定','无量纲','无量纲',{'fuselage','Clp'},[],1,0,-1e4,1e4,true,true,false,'direct','fuselage';
    'fuselage.Clr','偏航速度对机身滚转力矩的影响','机身滚转力矩随偏航角速度变化的系数。','气动模型设定','无量纲','无量纲',{'fuselage','Clr'},[],1,0,-1e4,1e4,true,true,false,'direct','fuselage';
    'fuselage.Cm0','机身零迎角俯仰力矩系数','机身俯仰力矩模型常值项。','气动模型设定','无量纲','无量纲',{'fuselage','Cm0'},[],1,0,-1e4,1e4,true,true,false,'direct','fuselage';
    'fuselage.Cmalpha','机身俯仰力矩迎角导数','INITIAL_MECHANISTIC_ASSUMPTION：缺少可靠机身或翼身组合俯仰矩数据，暂不使用原无来源经验斜率；真实贡献可能非零。','初期机理假设','1/rad','1/rad',{'fuselage','Cmalpha'},[],1,0,-1e4,1e4,true,true,false,'direct','fuselage';
    'fuselage.Cmq','机身俯仰阻尼导数','机身俯仰力矩随俯仰角速度变化的系数。','气动模型设定','无量纲','无量纲',{'fuselage','Cmq'},[],1,0,-1e4,1e4,true,true,false,'direct','fuselage';
    'fuselage.Cnbeta','机身偏航力矩侧滑导数','机身偏航力矩随侧滑角变化的系数。','气动模型设定','1/rad','1/rad',{'fuselage','Cnbeta'},[],1,0,-1e4,1e4,true,true,false,'direct','fuselage';
    'fuselage.Cnp','滚转速度对机身偏航力矩的影响','机身偏航力矩随滚转角速度变化的系数。','气动模型设定','无量纲','无量纲',{'fuselage','Cnp'},[],1,0,-1e4,1e4,true,true,false,'direct','fuselage';
    'fuselage.Cnr','机身偏航阻尼导数','机身偏航力矩随偏航角速度变化的系数。','气动模型设定','无量纲','无量纲',{'fuselage','Cnr'},[],1,0,-1e4,1e4,true,true,false,'direct','fuselage'};
catalog = add_rows(catalog, '机身', items);
end

function catalog = add_htail(catalog)
items = {
    'htail.S','平尾面积','平尾气动力使用的参考面积。','几何设定','m^2','m^2',{'htail','S'},[],1,0,0,Inf,false,true,false,'direct','htail';
    'htail.c','平尾弦长','平尾俯仰力矩使用的参考弦长。','几何设定','m','m',{'htail','c'},[],1,0,0,Inf,false,true,false,'direct','htail';
    'htail.rAC.x','平尾气动中心纵向位置','平尾气动力作用点的纵向位置。','几何设定','m','m',{'htail','rAC'},1,1,0,-Inf,Inf,true,true,false,'direct','htail';
    'htail.rAC.y','平尾气动中心横向位置','平尾气动力作用点的横向位置。','几何设定','m','m',{'htail','rAC'},2,1,0,-Inf,Inf,true,true,false,'direct','htail';
    'htail.rAC.z','平尾气动中心垂向位置','平尾气动力作用点的垂向位置。','几何设定','m','m',{'htail','rAC'},3,1,0,-Inf,Inf,true,true,false,'direct','htail';
    'htail.incidence','平尾安装角','CALIBRATED_EFFECTIVE_PARAMETER：与下洗在 70 m/s 平尾有效迎角中存在补偿关系，当前配平不能唯一识别真实值；不是 XV-15 实测参数。','标定有效参数','deg','rad',{'htail','incidence'},[],180/pi,0,-90,90,true,true,false,'direct','htail';
    'htail.downwashAlpha','平尾下洗系数','CALIBRATED_EFFECTIVE_PARAMETER：与平尾安装角在 70 m/s 有效迎角中存在补偿关系，当前配平不能唯一识别真实值；不是 XV-15 实测参数。','标定有效参数','无量纲','无量纲',{'htail','downwashAlpha'},[],1,0,-1e4,1e4,true,true,false,'direct','htail';
    'htail.CL0','平尾零迎角升力系数','平尾升力模型常值项。','气动模型设定','无量纲','无量纲',{'htail','CL0'},[],1,0,-1e4,1e4,true,true,false,'direct','htail';
    'htail.CLalpha','平尾升力线斜率','平尾升力随有效迎角变化的系数。','气动模型设定','1/rad','1/rad',{'htail','CLalpha'},[],1,0,-1e4,1e4,true,true,false,'direct','htail';
    'htail.CLmax','平尾最大升力系数','平尾升力系数饱和尺度。','气动模型设定','无量纲','无量纲',{'htail','CLmax'},[],1,0,0,Inf,false,true,false,'direct','htail';
    'htail.CLelevator','升降舵对平尾升力的影响','CALIBRATED_EFFECTIVE_PARAMETER：改变单位舵偏控制效率，不改变零升降舵基础载荷；不是 XV-15 实测参数。','标定有效参数','1/rad','1/rad',{'htail','CLelevator'},[],1,0,-1e4,1e4,true,true,false,'direct','htail';
    'htail.CD0','平尾零升阻力系数','平尾阻力模型基值。','气动模型设定','无量纲','无量纲',{'htail','CD0'},[],1,0,0,Inf,true,true,false,'direct','htail';
    'htail.kInduced','平尾诱导阻力系数','平尾阻力随升力平方变化的系数。','气动模型设定','无量纲','无量纲',{'htail','kInduced'},[],1,0,0,Inf,true,true,false,'direct','htail';
    'htail.Cm0','平尾零升俯仰力矩系数','平尾俯仰力矩模型常值项。','气动模型设定','无量纲','无量纲',{'htail','Cm0'},[],1,0,-1e4,1e4,true,true,false,'direct','htail';
    'htail.Cmelevator','升降舵对俯仰力矩的影响','升降舵对平尾俯仰力矩系数的影响系数。','气动模型设定','1/rad','1/rad',{'htail','Cmelevator'},[],1,0,-1e4,1e4,true,true,false,'direct','htail'};
catalog = add_rows(catalog, '平尾', items);
end

function catalog = add_vtail(catalog)
items = {
    'vtail.SEach','单侧垂尾面积','每片垂尾气动力使用的参考面积。','几何设定','m^2','m^2',{'vtail','SEach'},[],1,0,0,Inf,false,true,false,'direct','vtail';
    'vtail.xAC','垂尾气动中心纵向位置','垂尾气动力作用点的纵向位置。','几何设定','m','m',{'vtail','xAC'},[],1,0,-Inf,Inf,true,true,false,'direct','vtail';
    'vtail.yAC','垂尾气动中心横向半距','单侧垂尾气动力作用点横向距离。','几何设定','m','m',{'vtail','yAC'},[],1,0,0,Inf,true,true,false,'direct','vtail';
    'vtail.zAC','垂尾气动中心垂向位置','垂尾气动力作用点的垂向位置。','几何设定','m','m',{'vtail','zAC'},[],1,0,-Inf,Inf,true,true,false,'direct','vtail';
    'vtail.CD0','垂尾零侧力阻力系数','垂尾阻力模型基值。','气动模型设定','无量纲','无量纲',{'vtail','CD0'},[],1,0,0,Inf,true,true,false,'direct','vtail';
    'vtail.CYbeta','侧滑对垂尾侧向力的影响','垂尾侧力随侧滑角变化的系数。','气动模型设定','1/rad','1/rad',{'vtail','CYbeta'},[],1,0,-1e4,1e4,true,true,false,'direct','vtail';
    'vtail.CYrudder','方向舵对侧向力的影响','方向舵对垂尾侧力系数的影响系数。','气动模型设定','1/rad','1/rad',{'vtail','CYrudder'},[],1,0,-1e4,1e4,true,true,false,'direct','vtail'};
catalog = add_rows(catalog, '垂尾', items);
end

function catalog = add_controls(catalog)
defs = {
    'collectiveLim','总距';
    'cyclicLim','周期变距';
    'aileronLim','副翼';
    'elevatorLim','升降舵';
    'rudderLim','方向舵'};
for k = 1:size(defs,1)
    field = defs{k,1};
    label = defs{k,2};
    catalog = add(catalog, ['control.' field '.lower'], '操纵限幅', ...
        [label '下限'], [label '通道允许范围的下限。'], '操纵范围设定', ...
        'deg', 'rad', {'control',field}, 1, 'scalar', ...
        180/pi, 0, -180, 180, true, true, false, 'direct', field);
    catalog = add(catalog, ['control.' field '.upper'], '操纵限幅', ...
        [label '上限'], [label '通道允许范围的上限。'], '操纵范围设定', ...
        'deg', 'rad', {'control',field}, 2, 'scalar', ...
        180/pi, 0, -180, 180, true, true, false, 'direct', field);
end
end

function catalog = add_trim(catalog)
catalog = add(catalog, 'trim.residualTolerance', '配平计算', '配平残差容限', ...
    '判定配平残差是否满足要求的阈值。', '计算精度设置', ...
    '混合量纲', '混合量纲', {'trim','residualTolerance'}, [], ...
    'scalar', 1, 0, 0, Inf, false, true, false, 'direct', 'trim');
catalog = add(catalog, 'trim.maxIterations', '配平计算', '配平最大迭代次数', ...
    '配平求解器允许的最大迭代次数。', '计算精度设置', ...
    '次', '次', {'trim','maxIterations'}, [], ...
    'integer', 1, 0, 1, Inf, true, true, true, 'direct', 'trim');
names = {'俯仰角搜索尺度','总距搜索尺度','纵向周期变距搜索尺度'};
ids = {'theta','collective','cyclicLong'};
for k = 1:3
    catalog = add(catalog, ['trim.variableScale.' ids{k}], '配平计算', ...
        names{k}, [names{k} '，用于无量纲配平搜索变量缩放。'], ...
        '计算精度设置', 'deg', 'rad', {'trim','variableScale'}, ...
        k, 'scalar', 180/pi, 0, 0, Inf, false, true, false, ...
        'direct', 'trimScale');
end
end

function catalog = add_linear(catalog)
stateIds = {'u','v','w','p','q','r','phi','theta','psi'};
stateNames = {'纵向速度','侧向速度','垂向速度','滚转角速度', ...
    '俯仰角速度','偏航角速度','滚转角','俯仰角','偏航角'};
stateUnits = {'m/s','m/s','m/s','deg/s','deg/s','deg/s','deg','deg','deg'};
stateScales = [1 1 1 180/pi 180/pi 180/pi 180/pi 180/pi 180/pi];
for k = 1:9
    catalog = add(catalog, ['linear.dx.' stateIds{k}], '线性化计算', ...
        [stateNames{k} '差分步长'], [stateNames{k} '通道的中心差分扰动步长。'], ...
        '计算精度设置', stateUnits{k}, internal_unit_for_state(k), ...
        {'linear','dx'}, k, 'scalar', stateScales(k), 0, 0, Inf, ...
        false, true, false, 'direct', 'linearDx');
end
controlIds = {'collective','diffCollective','cyclicLong','diffCyclic', ...
    'aileron','elevator','rudder'};
controlNames = {'总距','差动总距','纵向周期变距','差动纵向周期变距', ...
    '副翼','升降舵','方向舵'};
for k = 1:7
    catalog = add(catalog, ['linear.du.' controlIds{k}], '线性化计算', ...
        [controlNames{k} '差分步长'], [controlNames{k} '通道的中心差分扰动步长。'], ...
        '计算精度设置', 'deg', 'rad', {'linear','du'}, k, ...
        'scalar', 180/pi, 0, 0, Inf, false, true, false, ...
        'direct', 'linearDu');
end
catalog = add(catalog, 'linear.stabilityTolerance', '线性化计算', ...
    '稳定性判据容限', '按特征值实部判定稳定性分类时使用的容限。', ...
    '计算精度设置', '1/s', '1/s', ...
    {'linear','stabilityTolerance'}, [], 'scalar', 1, 0, 0, Inf, ...
    false, true, false, 'direct', 'linear');
end

function unit = internal_unit_for_state(index)
if index <= 3
    unit = 'm/s';
elseif index <= 6
    unit = 'rad/s';
else
    unit = 'rad';
end
end

function catalog = add_rows(catalog, category, rows)
for i = 1:size(rows,1)
    subscript = rows{i,8};
    if isempty(subscript)
        subscript = [];
    end
    catalog = add(catalog, rows{i,1}, category, rows{i,2}, rows{i,3}, ...
        rows{i,4}, rows{i,5}, rows{i,6}, rows{i,7}, subscript, ...
        'scalar', rows{i,9}, rows{i,10}, rows{i,11}, rows{i,12}, ...
        rows{i,13}, rows{i,14}, rows{i,15}, rows{i,16}, rows{i,17});
end
end

function catalog = normalize_catalog_categories(catalog)
for k = 1:numel(catalog)
    id = catalog(k).id;
    if starts_with(id, 'mass.')
        catalog(k).category = '整机质量与惯量';
    end
    if any(strcmp(id, {'mass.mNac','mass.RH_mass','rotor.pivotX', ...
            'rotor.pivotY','rotor.pivotZ','rotor.RH_hub'}))
        catalog(k).category = '倾转机构';
    elseif starts_with(id, 'rotor.')
        if any(strcmp(id, {'rotor.R','rotor.Nb','rotor.chord', ...
                'rotor.rootCut','rotor.twistTip','rotor.bladeMass', ...
                'rotor.Jpolar'}))
            catalog(k).category = '旋翼几何';
        elseif strcmp(id, 'rotor.Omega')
            catalog(k).category = '旋翼运行';
        elseif contains(id, 'induced') || contains(id, 'flap') || ...
                any(strcmp(id, {'rotor.nRadial','rotor.nAzimuth'}))
            catalog(k).category = '旋翼入流与挥舞';
        else
            catalog(k).category = '旋翼气动';
        end
    elseif starts_with(id, 'control.')
        catalog(k).category = '操纵系统';
    end
end
end

function tf = starts_with(text, prefix)
tf = strncmp(text, prefix, numel(prefix));
end
