*  'advics.h' ...FORTRAN INCLUDE FILE
*                                                                      *
      CHARACTER*50 ADVIC1(4), ADVIC2(5), ADVIC3(4), ADVIC4(3), ADVIC5(1)
     +           , ADVIC6(3), ADVIC7(3), ADVIC8(3), ADVIC9(4), ADVC10(5)
     +           , ADVC11(3), ADVC12(5), ADVC13(5), ADVC14(45)
      COMMON /ADVICS/ ADVIC1, ADVIC2, ADVIC3, ADVIC4, ADVIC5, ADVIC6,
     +                ADVIC7, ADVIC8, ADVIC9, ADVC10, ADVC11, ADVC12,
     +                ADVC13, ADVC14

