*  'lists.h' ...FORTRAN INCLUDE FILE
*                                                                      *
      CHARACTER*50 LIST1(11), LIST2(7), LIST3(5), LIST4(2), LIST5(5),
     +             LIST6(2), LIST7(4), LIST8(2), LIST9(5), LIST10(4),
     +             LIST11(2), LIST12(5), LIST13(3)
      COMMON /LISTS/ LIST1, LIST2, LIST3, LIST4, LIST5, LIST6, LIST7,
     +               LIST8, LIST9, LIST10, LIST11, LIST12, LIST13

