function reference = params_xv15_public_reference()
%PARAMS_XV15_PUBLIC_REFERENCE Audited public XV-15 parameter records.
% This is a partial primary-source overlay, not a complete XV-15 model.
% PDF page numbers refer to the repository copies.  Printed page numbers
% are recorded separately because the scans include front matter.

ft2m = 0.3048;
in2m = 0.0254;
lb2kg = 0.45359237;
ft2sqm = ft2m^2;
slugft2_to_kgm2 = 1.3558179483314004;
d2r = pi/180;

records = repmat(empty_record(),0,1);
records(end+1) = record('mass.m',[],13000*lb2kg,'kg', ...
    'XV15_DIRECT','MASS','NASA_TM_X_62407.pdf',11,5, ...
    'Section 3.1.1, aircraft weights','13000','lb', ...
    '13000 lb * 0.45359237 kg/lb','design gross weight',false, ...
    'One documented weight state; not basic or research-mission empty.');

% At project betaM=0 the model is in helicopter mode.  Only the documented
% diagonal terms are replaced; the unavailable cross inertia remains the
% inherited generic value and is explicitly excluded from the direct claim.
IhelOriginal = [42400,14300,49500];
IairOriginal = [40500,13200,50300];
Ihel = IhelOriginal*slugft2_to_kgm2;
Iair = IairOriginal*slugft2_to_kgm2;
axisName = {'roll','pitch','yaw'};
for k = 1:3
    records(end+1) = record('mass.I0',[k k],Ihel(k),'kg m^2', ...
        'XV15_DIRECT','INERTIA','NASA_TM_X_62407.pdf',15,12, ...
        ['Section 3.1.3, ',axisName{k},' inertia table'], ...
        sprintf('%g',IhelOriginal(k)),'slug ft^2', ...
        'value * 1.3558179483314004 kg m^2/(slug ft^2)', ...
        '13000 lb, helicopter configuration',false, ...
        'Diagonal only; cross inertia is not reported in this table.'); %#ok<AGROW>
    slope = (Ihel(k)-Iair(k))/(pi/2);
    records(end+1) = record('mass.KI',[k k],slope,'kg m^2/rad', ...
        'XV15_DERIVED','INERTIA','NASA_TM_X_62407.pdf',15,12, ...
        ['Section 3.1.3 endpoint difference, ',axisName{k}], ...
        sprintf('helicopter %g; airplane %g', ...
        IhelOriginal(k),IairOriginal(k)), ...
        'slug ft^2', ...
        '(I_helicopter-I_airplane)*1.3558179483314004/(pi/2)', ...
        'linear interpolation imposed by current low-order inertia law',true, ...
        'Derived endpoint slope; not evidence that the real variation is linear.'); %#ok<AGROW>
end

records(end+1) = record('rotor.R',[],12.5*ft2m,'m', ...
    'XV15_DIRECT','GEOMETRY','NASA_TM_X_62407.pdf',20,17, ...
    'Section 3.7, 25 ft rotor diameter','25','ft diameter', ...
    '25 ft * 0.3048 / 2','XV-15 nominal rotor',false,'');
records(end+1) = record('rotor.Nb',[],3,'1', ...
    'XV15_DIRECT','GEOMETRY','NASA_TM_X_62407.pdf',20,17, ...
    'Section 3.7, number of blades per rotor','3','count', ...
    'identity','XV-15 nominal rotor',false,'');
records(end+1) = record('rotor.Omega',[],565*2*pi/60,'rad/s', ...
    'XV15_DIRECT','ROTOR_AERO','NASA_TM_X_62407.pdf',22,19, ...
    'Section 3.8, hover/helicopter nominal rpm','565','rpm', ...
    '565 rpm * 2*pi/60','hover/helicopter reference only',true, ...
    ['The current scalar interface cannot also represent the documented ' ...
     '458 rpm airplane value; the overlay therefore uses the hover value.']);
records(end+1) = record('rotor.chord',[],14*in2m,'m', ...
    'XV15_DIRECT','GEOMETRY','NASA_TM_X_62407.pdf',20,17, ...
    'Section 3.7, blade chord','14','in', ...
    '14 in * 0.0254','XV-15 nominal rotor',false,'');
records(end+1) = record('rotor.twistTip',[],-45*d2r,'rad', ...
    'XV15_DIRECT','ROTOR_AERO','NASA_TM_81244.pdf',4,2, ...
    'Design Characteristics, 45 deg root-to-tip blade twist','45', ...
    'deg magnitude','-45 deg * pi/180', ...
    'root-to-tip aerodynamic twist; negative toward tip',true, ...
    'Sign follows the project linear twist convention.');
records(end+1) = record('rotor.pivotY',[],0.5*32.17*ft2m,'m', ...
    'XV15_DERIVED','GEOMETRY','NASA_TM_X_62407.pdf',15,12, ...
    'Section 3.3 wing span footnote a','32.17','ft', ...
    '32.17 ft * 0.3048 / 2', ...
    'half distance between rotor centerlines at tilt axes',false, ...
    'Direct span divided by two for the symmetric body-y coordinate.');

records(end+1) = record('wing.S',[],169*ft2sqm,'m^2', ...
    'XV15_DIRECT','GEOMETRY','NASA_TM_X_62407.pdf',15,12, ...
    'Section 3.3 dimensions table','169.0','ft^2', ...
    '169.0 ft^2 * 0.09290304','documented wing reference area',false,'');
records(end+1) = record('wing.b',[],32.17*ft2m,'m', ...
    'XV15_DIRECT','GEOMETRY','NASA_TM_X_62407.pdf',15,12, ...
    'Section 3.3 dimensions table and footnote a','32.17','ft', ...
    '32.17 ft * 0.3048','between rotor centerlines at tilt axes',true, ...
    'Used as the present low-order wing span reference.');
records(end+1) = record('wing.c',[],5.25*ft2m,'m', ...
    'XV15_DIRECT','GEOMETRY','NASA_TM_X_62407.pdf',15,12, ...
    'Section 3.3 mean aerodynamic chord','5.25','ft', ...
    '5.25 ft * 0.3048','wing mean aerodynamic chord',false,'');

records(end+1) = record('htail.S',[],50.25*ft2sqm,'m^2', ...
    'XV15_DIRECT','GEOMETRY','NASA_TM_X_62407.pdf',15,12, ...
    'Section 3.3 horizontal-tail area','50.25','ft^2', ...
    '50.25 ft^2 * 0.09290304','horizontal tail total area',false,'');
records(end+1) = record('htail.c',[],3.92*ft2m,'m', ...
    'XV15_DIRECT','GEOMETRY','NASA_TM_X_62407.pdf',15,12, ...
    'Section 3.3 horizontal-tail mean chord','3.92','ft', ...
    '3.92 ft * 0.3048','horizontal tail mean aerodynamic chord',false,'');
records(end+1) = record('vtail.SEach',[],0.5*50.5*ft2sqm,'m^2', ...
    'XV15_DERIVED','GEOMETRY','NASA_TM_X_62407.pdf',15,12, ...
    'Section 3.3 vertical-tail total area','50.5','ft^2 total', ...
    '50.5 ft^2 * 0.09290304 / 2','symmetric twin-tail split',true, ...
    'Equal per-fin split is imposed by the present symmetric twin-tail model.');
records(end+1) = record('vtail.c',[],3.72*ft2m,'m', ...
    'XV15_DIRECT','GEOMETRY','NASA_TM_X_62407.pdf',15,12, ...
    'Section 3.3 vertical-tail mean aerodynamic chord','3.72','ft', ...
    '3.72 ft * 0.3048','vertical tail mean aerodynamic chord',false, ...
    'This field is metadata in the current model and does not affect loads.');

records(end+1) = record('control.elevatorLim',[],[-20 20]*d2r,'rad', ...
    'XV15_DIRECT','CONTROL_LIMIT','NASA_TM_X_62407.pdf',17,14, ...
    'Section 3.4 movable-surface table','+/-20','deg', ...
    '[-20 20] deg * pi/180','elevator surface deflection',false,'');
records(end+1) = record('control.rudderLim',[],[-20 20]*d2r,'rad', ...
    'XV15_DIRECT','CONTROL_LIMIT','NASA_TM_X_62407.pdf',17,14, ...
    'Section 3.4 movable-surface table','+/-20','deg', ...
    '[-20 20] deg * pi/180','rudder surface deflection',false,'');

reference.variantName = 'XV15_PUBLIC_REFERENCE_PARTIAL';
reference.creationMethod = 'PRIMARY_SOURCE_TRANSCRIPTION_AND_UNIT_CONVERSION';
reference.records = records;
reference.sourceManifest = { ...
    'references/NASA_TM_X_62407.pdf'; ...
    'references/NASA_TM_81244.pdf'};
reference.claimBoundary = ['Partial public XV-15 values only.  Geometry, ' ...
    'mass state, coefficient families, component positions, controls, and ' ...
    'inertias not listed here remain unknown or inherited generic values.'];
end

function r = empty_record()
r = struct('path','','subscripts',[],'valueSI',[],'unitSI','', ...
    'sourceClass','REFERENCE','claimClass','','roleClass','', ...
    'sourceFile','','sourceTitle','','reportNumber','','authors','', ...
    'publicationYear',NaN,'pdfPage',NaN,'printedPage',NaN,'locator','', ...
    'originalValue','','originalUnit','','conversion','', ...
    'applicableConfiguration','','manualReview',false, ...
    'applyToModel',true,'note','');
end

function r = record(path,subscripts,valueSI,unitSI,claimClass,roleClass, ...
        sourceFile,pdfPage,printedPage,locator,originalValue, ...
        originalUnit,conversion,configuration,manualReview,note)
r = empty_record();
r.path = path;
r.subscripts = subscripts;
r.valueSI = valueSI;
r.unitSI = unitSI;
r.claimClass = claimClass;
r.roleClass = roleClass;
r.sourceFile = sourceFile;
[r.sourceTitle,r.reportNumber,r.authors,r.publicationYear] = ...
    source_metadata(sourceFile);
r.pdfPage = pdfPage;
r.printedPage = printedPage;
r.locator = locator;
r.originalValue = originalValue;
r.originalUnit = originalUnit;
r.conversion = conversion;
r.applicableConfiguration = configuration;
r.manualReview = manualReview;
r.note = note;
end

function [titleText,reportNumber,authors,year] = source_metadata(sourceFile)
switch sourceFile
    case 'NASA_TM_X_62407.pdf'
        titleText = ['NASA/Army XV-15 Tilt Rotor Research Aircraft ' ...
            'Familiarization Document'];
        reportNumber = 'NASA TM X-62407 / A-5870';
        authors = ['Tilt Rotor Project Office Staff; coordinated by ' ...
            'Martin Maisel'];
        year = 1975;
    case 'NASA_TM_81244.pdf'
        titleText = 'The XV-15 Tilt Rotor Research Aircraft';
        reportNumber = 'NASA TM-81244 / AVRADCOM-TR-80-A-15 / A-8343';
        authors = 'D. C. Dugan; R. G. Erhart; L. G. Schroers';
        year = 1980;
    otherwise
        titleText = ''; reportNumber = ''; authors = ''; year = NaN;
end
end
