function reference = params_xv15_public_reference_second_pass()
%PARAMS_XV15_PUBLIC_REFERENCE_SECOND_PASS Second-pass public XV-15 audit.
% This registry extends the PR #53 provenance work without modifying the
% legacy reference function or params_nominal.m.  Only records tagged
% SAFE_DIRECT_OVERLAY are eligible for automatic application by the V2
% overlay.  Interface-blocked and model-form records remain evidence only.

ft2m = 0.3048;
in2m = 0.0254;
slugft2_to_kgm2 = 1.3558179483314004;
d2r = pi/180;

records = repmat(empty_record(),0,1);

cr2017Title = 'Hover Performance of the XV-15 Tilt Rotor Aircraft';
cr2017Number = 'NASA CR-2017-219486';
cr2017URL = ['https://rotorcraft.arc.nasa.gov/Publications/files/' ...
    'NASA%20CR-2017-219486_Final.pdf'];

% Table A-1 reports a 1.06 ft blade cutout radius and a 12.5 ft rotor
% radius.  The present model stores rootCut as r/R, so the conversion is
% directly homologous to the existing field semantics.
records(end+1) = record('rotor.rootCut',[],1.06/12.5,'1', ...
    'XV15_DERIVED','SAFE_DIRECT_OVERLAY',true, ...
    cr2017Title,cr2017Number,cr2017URL,'Table A-1', ...
    '1.06 ft cutout / 12.5 ft radius','ft/ft', ...
    '1.06 / 12.5','full-scale original metal-blade XV-15 proprotor', ...
    ['Current rootCut is the aerodynamic integration start, which is ' ...
     'compatible with the reported blade cutout-radius definition.']);

% Table A-1 reports blade flapping inertia per blade.  The current model
% uses P.rotor.Ib as a per-blade flapping inertia in the flap equation.
records(end+1) = record('rotor.Ib',[],105*slugft2_to_kgm2,'kg m^2', ...
    'XV15_DIRECT','SAFE_DIRECT_OVERLAY',true, ...
    cr2017Title,cr2017Number,cr2017URL,'Table A-1', ...
    '105','slug ft^2', ...
    '105 * 1.3558179483314004','full-scale original metal-blade XV-15 proprotor', ...
    'Per-blade flapping inertia; directly matches the present Ib usage.');

% Rotor speed is explicitly configuration dependent.  A single scalar
% Omega cannot represent all three documented operating points.
records(end+1) = record('rotor.Omega',[],565*2*pi/60,'rad/s', ...
    'XV15_DIRECT','INTERFACE_BLOCKED_MODE_SCHEDULE',false, ...
    cr2017Title,cr2017Number,cr2017URL,'Table A-1', ...
    '565','rpm','565 * 2*pi/60','helicopter/hover', ...
    'Do not apply globally: the same source reports 534 rpm in conversion and 458 rpm in airplane mode.');
records(end+1) = record('rotor.Omega',[],534*2*pi/60,'rad/s', ...
    'XV15_DIRECT','INTERFACE_BLOCKED_MODE_SCHEDULE',false, ...
    cr2017Title,cr2017Number,cr2017URL,'Table A-1', ...
    '534','rpm','534 * 2*pi/60','conversion', ...
    'Requires a nacelle-angle/flight-mode rotor-speed schedule rather than scalar P.rotor.Omega.');
records(end+1) = record('rotor.Omega',[],458*2*pi/60,'rad/s', ...
    'XV15_DIRECT','INTERFACE_BLOCKED_MODE_SCHEDULE',false, ...
    cr2017Title,cr2017Number,cr2017URL,'Table A-1', ...
    '458','rpm','458 * 2*pi/60','airplane', ...
    'Requires a nacelle-angle/flight-mode rotor-speed schedule rather than scalar P.rotor.Omega.');

% The reported blade is not constant-chord near the root: 17 in at the
% cuff root (0.0875R), tapering to the 14 in basic blade by 0.25R.
records(end+1) = record('rotor.chord',[],14*in2m,'m', ...
    'XV15_DIRECT','INTERFACE_BLOCKED_RADIAL_GEOMETRY',false, ...
    cr2017Title,cr2017Number,cr2017URL,'Table A-1', ...
    '14 basic; 17 cuff at 0.0875R tapering to 14 at 0.25R','in', ...
    '14 in * 0.0254 for the basic blade only', ...
    'full-scale original metal-blade XV-15 proprotor', ...
    'Do not collapse the cuff/taper into a single constant-chord field for quantitative validation.');

% The source documents -45 deg total twist but explicitly points to a
% non-linear radial distribution.  The present twistTip field creates a
% linear root-to-tip law, therefore automatic application is not homologous.
records(end+1) = record('rotor.twistTip',[],-45*d2r,'rad', ...
    'XV15_DIRECT','INTERFACE_BLOCKED_NONLINEAR_TWIST',false, ...
    cr2017Title,cr2017Number,cr2017URL,'Table A-1 and referenced twist distribution', ...
    '-45','deg total twist','-45 deg * pi/180', ...
    'full-scale original metal-blade XV-15 proprotor', ...
    'Current field enforces a linear twist law; preserve as evidence until radial twist is represented.');

records(end+1) = record('rotor.flapMax',[],12*d2r,'rad', ...
    'XV15_DIRECT','SEMANTIC_MISMATCH_METADATA_ONLY',false, ...
    cr2017Title,cr2017Number,cr2017URL,'Table A-1', ...
    '+/-12','deg design clearance','12 deg * pi/180', ...
    'full-scale original metal-blade XV-15 proprotor', ...
    ['The source value is mechanical flapping design clearance.  The ' ...
     'current flapMax field is compatibility metadata and is not the active flap-solver guard.']);

records(end+1) = record('rotor.precone',[],2.5*d2r,'rad', ...
    'XV15_DIRECT','MODEL_FIELD_MISSING',false, ...
    cr2017Title,cr2017Number,cr2017URL,'Table A-1', ...
    '2.5','deg','2.5 deg * pi/180', ...
    'full-scale original metal-blade XV-15 proprotor', ...
    'No homologous active field exists in the current low-order rotor model.');
records(end+1) = record('rotor.delta3',[],-15*d2r,'rad', ...
    'XV15_DIRECT','MODEL_FIELD_MISSING',false, ...
    cr2017Title,cr2017Number,cr2017URL,'Table A-1', ...
    '-15','deg','-15 deg * pi/180', ...
    'full-scale original metal-blade XV-15 proprotor', ...
    'Pitch-flap coupling is documented but is not represented by an active model parameter.');
records(end+1) = record('rotor.lockNumber',[],3.83,'1', ...
    'XV15_DIRECT','MODEL_FIELD_MISSING',false, ...
    cr2017Title,cr2017Number,cr2017URL,'Table A-1', ...
    '3.83','1','identity', ...
    'full-scale original metal-blade XV-15 proprotor', ...
    'Useful consistency check for blade mass/aerodynamic-property reconstruction; no active field exists.');
records(end+1) = record('rotor.mastMomentSpringRate',[], ...
    2700*0.1129848290276167/(pi/180),'N m/rad', ...
    'XV15_DIRECT','MODEL_FIELD_MISSING',false, ...
    cr2017Title,cr2017Number,cr2017URL,'Table A-1', ...
    '2700','in lbf/deg', ...
    '2700 * 0.1129848290276167 / (pi/180)', ...
    'full-scale original metal-blade XV-15 proprotor', ...
    'The present first-harmonic flap model has no homologous gimbal/mast spring-rate parameter.');

% GTRS documents data-table families that cannot be represented by the
% current scalar coefficient model.  These entries deliberately have NaN
% valueSI and remain evidence-only until a lookup-table interface exists.
gtrsTitle = 'A Mathematical Model for Real Time Flight Simulation of a Generic Tilt-Rotor Aircraft';
gtrsNumber = 'NASA CR-166536A';
gtrsURL = 'https://rotorcraft.arc.nasa.gov/Publications/files/CR-166536_882.pdf';
records(end+1) = record('fuselage.aeroTables',[],NaN,'table', ...
    'XV15_SOURCE_TABLE','TABLE_MODEL_REQUIRED',false, ...
    gtrsTitle,gtrsNumber,gtrsURL,'Subsystem 3; Appendix B pp. B-26 through B-30', ...
    'XV-15 wind-tunnel coefficient tables','table','none', ...
    'XV-15 airframe reference within GTRS', ...
    ['For |alpha| and |beta| up to about 20 deg the report states the ' ...
     'fuselage coefficients are based on XV-15 wind-tunnel data; current scalar polynomials cannot ingest the tables directly.']);
records(end+1) = record('wing.aeroTables',[],NaN,'table', ...
    'XV15_SOURCE_TABLE','TABLE_MODEL_REQUIRED',false, ...
    gtrsTitle,gtrsNumber,gtrsURL,'Subsystem 4 and Appendix B wing-pylon data', ...
    'wing-pylon lift/drag/pitching-moment tables','table','none', ...
    'XV-15/GTRS wing-pylon reference', ...
    'Requires a lookup-table or fitted-surface layer rather than replacing one scalar CLalpha/CD0/Cm0 value.');

reference.variantName = 'XV15_PUBLIC_REFERENCE_SECOND_PASS';
reference.creationMethod = 'PRIMARY_PUBLIC_SOURCE_AUDIT_WITH_INTERFACE_GATING';
reference.records = records;
reference.safeApplyPaths = unique({records([records.applyToModel]).path}.','stable');
reference.sourceManifest = {cr2017URL; gtrsURL; ...
    'https://ntrs.nasa.gov/citations/19860005773'; ...
    'https://ntrs.nasa.gov/citations/19870014976'; ...
    'https://ntrs.nasa.gov/citations/19840026374'};
reference.claimBoundary = [ ...
    'Second-pass public-data registry. Only semantically homologous fields ' ...
    'are eligible for automatic overlay. Mode schedules, radial blade ' ...
    'geometry, nonlinear twist, missing rotor states, and GTRS aerodynamic ' ...
    'tables are explicitly blocked from scalar substitution.'];
end

function r = empty_record()
r = struct('path','','subscripts',[],'valueSI',[],'unitSI','', ...
    'claimClass','','disposition','','applyToModel',false, ...
    'sourceTitle','','reportNumber','','sourceURL','','locator','', ...
    'originalValue','','originalUnit','','conversion','', ...
    'applicableConfiguration','','note','');
end

function r = record(path,subscripts,valueSI,unitSI,claimClass,disposition, ...
        applyToModel,sourceTitle,reportNumber,sourceURL,locator, ...
        originalValue,originalUnit,conversion,configuration,note)
r = empty_record();
r.path = path;
r.subscripts = subscripts;
r.valueSI = valueSI;
r.unitSI = unitSI;
r.claimClass = claimClass;
r.disposition = disposition;
r.applyToModel = applyToModel;
r.sourceTitle = sourceTitle;
r.reportNumber = reportNumber;
r.sourceURL = sourceURL;
r.locator = locator;
r.originalValue = originalValue;
r.originalUnit = originalUnit;
r.conversion = conversion;
r.applicableConfiguration = configuration;
r.note = note;
end
