function [P13, manifest] = params_generic_trim_optimized()
%PARAMS_GENERIC_TRIM_OPTIMIZED Frozen joint design/effective-aero model C2.
% C2 inherits the C1 geometry and adds one bounded effective tail-control
% parameter.  CLelevator is calibrated-effective, not a measured derivative.

[P13, c1] = params_generic_geometry_optimized();
baselineValue = P13.base.htail.CLelevator;
P13.base.htail.CLelevator = 2.35;

effective = struct('path','htail.CLelevator', ...
    'baselineValue',baselineValue,'frozenValue',2.35, ...
    'lowerBound',1.60,'upperBound',2.40,'unit','1/rad', ...
    'sourceClass','ASSUMED_MODEL_PARAMETER', ...
    'claimClass','CALIBRATED_EFFECTIVE', ...
    'roleClass','CONTROL_EFFECTIVENESS', ...
    'selectionSet','DESIGN_FEASIBILITY_SET_9_POINT', ...
    'validationUse','FROZEN_BEFORE_VALIDATION', ...
    'note',['Effective low-order elevator derivative.  It absorbs unresolved ' ...
        'tail/control physics and is not an XV-15 measured coefficient.']);

manifest = c1;
manifest.variantName = 'GENERIC_TRIM_OPTIMIZED_C2';
manifest.parentVariant = c1.variantName;
manifest.optimizationClass = 'BOUNDED_GEOMETRY_PLUS_ONE_EFFECTIVE_AERO';
manifest.records = [c1.records; effective];
manifest.optimizedFields = {manifest.records.path}.';
manifest.rejectedCorrelatedFields = {'htail.downwashAlpha'};
manifest.identifiabilityDecision = [ ...
    'downwashAlpha was frozen at its baseline because simultaneous tail ' ...
    'effectiveness/downwash adjustment was judged insufficiently identifiable.'];
manifest.claimBoundary = ['Generic low-order-model design plus one effective ' ...
    'control derivative; not a complete or validated XV-15 model.'];
end
