function auditTable = audit_xv15_v1_baseline_model_identity(outputDir)
%AUDIT_XV15_V1_BASELINE_MODEL_IDENTITY Guard the pure-M0 XV-15 V1 path.
%
% This is a static verification gate, not a physics calculation.  It checks
% that the historical pure-M0 runner still calls the production
% rotor_model_bemt directly and has not silently acquired known post-
% validation model extensions.  A failed check aborts the canonical V1 run.

rootDir = fileparts(fileparts(mfilename('fullpath')));
if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(rootDir, 'results', 'xv15_validation_baseline');
end
if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

baselinePath = fullfile(rootDir, 'analysis', ...
    'run_xv15_metal_hover_validation.m');
if ~exist(baselinePath, 'file')
    error('audit_xv15_v1_baseline_model_identity:MissingBaselineRunner', ...
        'Missing baseline runner: %s', baselinePath);
end

src = fileread(baselinePath);
srcLower = lower(src);

checkName = {};
passed = [];
evidence = {};

[checkName, passed, evidence] = add_check(checkName, passed, evidence, ...
    'DIRECT_PRODUCTION_BEMT_CALL', ...
    contains(srcLower, 'rotor_model_bemt('), ...
    'run_xv15_metal_hover_validation must call rotor_model_bemt directly');

forbidden = { ...
    'rotor_model_bemt_section_aero', ...
    'build_xv15_c81_low_order_section_aero', ...
    'alpha0l', ...
    'enablecompressibilitycorrection', ...
    'prandtl', ...
    'mangler', ...
    'prescribed_wake', ...
    'prescribed wake', ...
    'biot-savart', ...
    'biot_savart'};

for k = 1:numel(forbidden)
    token = forbidden{k};
    [checkName, passed, evidence] = add_check(checkName, passed, evidence, ...
        ['FORBID_' upper(regexprep(token, '[^a-zA-Z0-9]', '_'))], ...
        ~contains(srcLower, lower(token)), ...
        ['baseline source must not contain extension token: ' token]);
end

[checkName, passed, evidence] = add_check(checkName, passed, evidence, ...
    'NO_XV15_SECTION_AERO_OVERWRITE', ...
    ~(contains(srcLower, 'p.rotor.liftslope =') || ...
      contains(srcLower, 'ptemplate.rotor.liftslope =') || ...
      contains(srcLower, 'p.rotor.clmax =') || ...
      contains(srcLower, 'p.rotor.cd0 =') || ...
      contains(srcLower, 'p.rotor.kcd =')), ...
    ['pure M0 baseline retains generic liftSlope/CLmax/CD0/kCD rather ' ...
     'than reconstructing XV-15 section aero']);

checkName = checkName(:);
passed = logical(passed(:));
evidence = evidence(:);
modelIdentity = repmat({'M0_PRODUCTION_LOW_ORDER'}, numel(checkName), 1);
auditTable = table(checkName, passed, modelIdentity, evidence);
writetable(auditTable, fullfile(outputDir, ...
    'XV15_V1_M0_MODEL_IDENTITY_AUDIT.csv'));

if ~all(passed)
    failed = strjoin(checkName(~passed), ', ');
    error('audit_xv15_v1_baseline_model_identity:IdentityGateFailed', ...
        'Pure-M0 identity gate failed: %s', failed);
end
end

function [names, flags, evidence] = add_check(names, flags, evidence, ...
        name, flag, detail)
names{end+1,1} = name; %#ok<AGROW>
flags(end+1,1) = flag; %#ok<AGROW>
evidence{end+1,1} = detail; %#ok<AGROW>
end
