function results = audit_m1_model_form_instance_separation(outputDir)
%AUDIT_M1_MODEL_FORM_INSTANCE_SEPARATION Verify model/instance separation.

rootDir=fileparts(fileparts(mfilename('fullpath')));
if nargin<1 || isempty(outputDir)
    outputDir=fullfile(rootDir,'results','m1_model_form_instance_separation');
end
if ~exist(outputDir,'dir'), mkdir(outputDir); end

%% 1) Frozen XV-15 Stage-3 identity is the validation-instance oracle.
stage3=run_m1_stage3_corrigan_stall_delay(fullfile(outputDir,'stage3_reference'));
ref=stage3.points(strcmp(stage3.points.mode,'CORRIGAN_GENERIC_N1'),:);
if height(ref)~=6
    error('audit_m1_model_form_instance_separation:ReferenceCount', ...
        'Expected six frozen Corrigan n=1 reference points.');
end
P=params_nominal();
cfg=struct('instanceType','XV15_VALIDATION_INSTANCE','corriganMode','N1');
identity=table();
for k=1:height(ref)
    Pk=P;
    Vtip=ref.Vtip_fps(k)*0.3048;
    Pk.rotor.Omega=Vtip/3.81;
    out=rotor_m1_hover_model_form(Pk,ref.collective75_deg(k)*pi/180,cfg);
    one=table(ref.collective75_deg(k),ref.CT_model(k),out.CT, ...
        abs(ref.CT_model(k)-out.CT),ref.CP_model(k),out.CP, ...
        abs(ref.CP_model(k)-out.CP),ref.FM_model(k),out.FM, ...
        abs(ref.FM_model(k)-out.FM),out.physicalConverged, ...
        'VariableNames',{'collective75_deg','CT_frozen','CT_extracted','CT_absDiff', ...
        'CP_frozen','CP_extracted','CP_absDiff','FM_frozen','FM_extracted', ...
        'FM_absDiff','physicalConverged'});
    identity=[identity;one]; %#ok<AGROW>
end
writetable(identity,fullfile(outputDir,'M1_MODEL_FORM_XV15_IDENTITY.csv'));
maxIdentityDiff=max([identity.CT_absDiff;identity.CP_absDiff;identity.FM_absDiff]);
if ~all(identity.physicalConverged) || ...
        ~(isfinite(maxIdentityDiff) && maxIdentityDiff<=1e-10)
    error('audit_m1_model_form_instance_separation:IdentityDrift', ...
        'Extracted model form drifted from frozen validation identity: %.12g.', ...
        maxIdentityDiff);
end

%% 2) Generic zero-enhancement limit must reproduce production M0 hover.
Pg=params_nominal();
% NUMERICAL ONLY: increase the maximum iteration allowance symmetrically.
% Tolerances, relaxation, equations and physical parameters are unchanged.
Pg.rotor.inducedMaxIter=200;
x=zeros(9,1); betaM=0; side=-1; cgShift=zeros(3,1);
collectivesDeg=[10;12;14];
m0limit=table();
for k=1:numel(collectivesDeg)
    theta=collectivesDeg(k)*pi/180;
    ctrl=struct('collective',theta,'cyclicLong',0);
    [~,~,m0]=rotor_model_bemt(x,ctrl,betaM,side,cgShift,Pg);
    off=rotor_m1_hover_model_form(Pg,theta, ...
        struct('instanceType','GENERIC_NOMINAL_INSTANCE','corriganMode','OFF'));
    dT=abs(off.thrust-m0.thrust)/max(abs(m0.thrust),1);
    dQ=abs(off.torque-m0.torque)/max(abs(m0.torque),1);
    dVi=abs(off.inducedVelocity-m0.inducedVelocity)/max(abs(m0.inducedVelocity),1);
    one=table(collectivesDeg(k),m0.thrust,off.thrust,dT,m0.torque,off.torque,dQ, ...
        m0.inducedVelocity,off.inducedVelocity,dVi,m0.physicalConverged, ...
        off.physicalConverged, ...
        'VariableNames',{'rootCollective_deg','M0_thrust_N','OFF_thrust_N','T_relDiff', ...
        'M0_torque_Nm','OFF_torque_Nm','Q_relDiff','M0_vi_mps','OFF_vi_mps', ...
        'vi_relDiff','M0_physicalConverged','OFF_physicalConverged'});
    m0limit=[m0limit;one]; %#ok<AGROW>
end
writetable(m0limit,fullfile(outputDir,'M1_GENERIC_M0_LIMIT_IDENTITY.csv'));
maxM0LimitRelDiff=max([m0limit.T_relDiff;m0limit.Q_relDiff;m0limit.vi_relDiff]);
if ~all(m0limit.M0_physicalConverged) || ~all(m0limit.OFF_physicalConverged) || ...
        ~(isfinite(maxM0LimitRelDiff) && maxM0LimitRelDiff<=1e-8)
    error('audit_m1_model_form_instance_separation:M0LimitDrift', ...
        'Generic OFF limit drifted from production M0 hover: %.12g.', ...
        maxM0LimitRelDiff);
end

%% 3) Explicit parameter/semantic separation table.
name={'rotor_R_m';'rootCut_R';'chord_representation';'twist_representation'; ...
    'section_aero';'pitch_reference';'forward_flight_support'; ...
    'cyclic_support';'nacelle_angle_support';'aircraft_identity'};
generic={sprintf('%.12g',Pg.rotor.R);sprintf('%.12g',Pg.rotor.rootCut); ...
    'CONSTANT_P_ROTOR_CHORD';'LINEAR_P_ROTOR_TWISTTIP'; ...
    'GENERIC_SCALAR_TANH_CL_PLUS_CD_POLAR_OPTIONAL_CORRIGAN_N1'; ...
    'ROOT_COLLECTIVE';'NO_HOVER_ONLY';'NO';'BETA_M_ZERO_ONLY'; ...
    'GENERIC_CONCEPT_PARAMS_NOMINAL'};
xv15={'3.81';'0.0875';'XV15_SOURCE_INFORMED_RADIAL_CHORD'; ...
    'XV15_NONLINEAR_METAL_BLADE_TWIST';'XV15_FOUR_REGION_C81_PLUS_CORRIGAN_N1'; ...
    'THETA75';'NO_HOVER_ONLY';'NO';'BETA_M_ZERO_ONLY'; ...
    'XV15_VALIDATION_INSTANCE'};
exportToGeneric={'NO';'NO';'NO';'NO';'NO';'NO';'N/A';'N/A';'N/A';'NO'};
contract=table(name,generic,xv15,exportToGeneric, ...
    'VariableNames',{'field','genericInstance','xv15ValidationInstance', ...
    'xv15ValueMayExportToGeneric'});
writetable(contract,fullfile(outputDir,'M1_MODEL_FORM_INSTANCE_CONTRACT.csv'));

%% 4) Generic N1 smoke point. No XV-15 data are read in this branch.
outGeneric=rotor_m1_hover_model_form(Pg,10*pi/180, ...
    struct('instanceType','GENERIC_NOMINAL_INSTANCE','corriganMode','N1'));
if ~outGeneric.physicalConverged || ~all(isfinite([outGeneric.CT,outGeneric.CP,outGeneric.FM]))
    error('audit_m1_model_form_instance_separation:GenericSmoke', ...
        'Generic nominal M1 hover instance did not produce a supported 10-deg point.');
end
genericSmoke=table(10,outGeneric.CT,outGeneric.CP,outGeneric.FM, ...
    outGeneric.thrust,outGeneric.power,outGeneric.inducedVelocity, ...
    {outGeneric.parameterBoundary}, ...
    'VariableNames',{'rootCollective_deg','CT','CP','FM','thrust_N','power_W', ...
    'inducedVelocity_mps','claimBoundary'});
writetable(genericSmoke,fullfile(outputDir,'M1_GENERIC_NOMINAL_SMOKE.csv'));

metadata=table( ...
    {'stage';'xv15_identity_gate';'generic_m0_limit_gate'; ...
     'generic_induced_max_iter';'numerical_change_role'; ...
     'xv15_parameters_exported_to_generic';'generic_instance_parameter_source'; ...
     'claim_boundary'}, ...
    {'AIRCRAFT_PROPAGATION_GATE_1';sprintf('MAX_ABS_DIFF_%.12g',maxIdentityDiff); ...
     sprintf('MAX_REL_DIFF_%.12g',maxM0LimitRelDiff);'200'; ...
     'MAX_ITER_CAP_ONLY_SAME_TOLERANCE_RELAXATION_AND_PHYSICS';'NO'; ...
     'PARAMS_NOMINAL_ONLY_PLUS_PREDECLARED_CORRIGAN_N1_MODEL_FORM'; ...
     'MODEL_FORM_TRANSFER_NOT_XV15_AIRCRAFT_VALIDATION_HOVER_ONLY'}, ...
    'VariableNames',{'name','value'});
writetable(metadata,fullfile(outputDir,'M1_MODEL_FORM_INSTANCE_METADATA.csv'));

results.identity=identity;
results.maxIdentityDiff=maxIdentityDiff;
results.m0limit=m0limit;
results.maxM0LimitRelDiff=maxM0LimitRelDiff;
results.contract=contract;
results.genericSmoke=genericSmoke;
results.metadata=metadata;
save(fullfile(outputDir,'M1_MODEL_FORM_INSTANCE_RESULTS.mat'),'results');
end
