function results = audit_m1_model_form_instance_separation(outputDir)
%AUDIT_M1_MODEL_FORM_INSTANCE_SEPARATION Verify no XV-15 parameter leakage.

rootDir=fileparts(fileparts(mfilename('fullpath')));
if nargin<1 || isempty(outputDir)
    outputDir=fullfile(rootDir,'results','m1_model_form_instance_separation');
end
if ~exist(outputDir,'dir'), mkdir(outputDir); end

% 1) Frozen Stage-3 identity is the validation-instance oracle.
stage3=run_m1_stage3_corrigan_stall_delay(fullfile(outputDir,'stage3_reference'));
ref=stage3.points(strcmp(stage3.points.mode,'CORRIGAN_GENERIC_N1'),:);
if height(ref)~=6
    error('audit_m1_model_form_instance_separation:ReferenceCount', ...
        'Expected six frozen Corrigan n=1 reference points.');
end

P=params_nominal();
cfg=struct('instanceType','XV15_VALIDATION_INSTANCE');
identity=table();
for k=1:height(ref)
    Pk=P;
    Vtip=ref.Vtip_fps(k)*0.3048;
    Pk.rotor.Omega=Vtip/3.81;
    out=rotor_m1_hover_model_form(Pk,ref.collective75_deg(k)*pi/180,cfg);
    one=table(ref.collective75_deg(k),ref.CT_model(k),out.CT, ...
        abs(ref.CT_model(k)-out.CT),ref.CP_model(k),out.CP, ...
        abs(ref.CP_model(k)-out.CP),ref.FM_model(k),out.FM, ...
        abs(ref.FM_model(k)-out.FM),out.physicalConverged, ...
        'VariableNames',{'collective75_deg','CT_frozen','CT_extracted','CT_absDiff', ...
        'CP_frozen','CP_extracted','CP_absDiff','FM_frozen','FM_extracted', ...
        'FM_absDiff','physicalConverged'});
    identity=[identity;one]; %#ok<AGROW>
end
writetable(identity,fullfile(outputDir,'M1_MODEL_FORM_XV15_IDENTITY.csv'));
maxIdentityDiff=max([identity.CT_absDiff;identity.CP_absDiff;identity.FM_absDiff]);
if ~all(identity.physicalConverged) || ...
        ~(isfinite(maxIdentityDiff) && maxIdentityDiff<=1e-10)
    error('audit_m1_model_form_instance_separation:IdentityDrift', ...
        'Extracted model form drifted from frozen validation identity: %.12g.', ...
        maxIdentityDiff);
end

% 2) Explicit parameter/semantic separation table.
Pg=params_nominal();
name={'rotor_R_m';'rootCut_R';'chord_representation';'twist_representation'; ...
    'section_aero';'pitch_reference';'forward_flight_support'; ...
    'cyclic_support';'nacelle_angle_support';'aircraft_identity'};
generic={sprintf('%.12g',Pg.rotor.R);sprintf('%.12g',Pg.rotor.rootCut); ...
    'CONSTANT_P_ROTOR_CHORD';'LINEAR_P_ROTOR_TWISTTIP'; ...
    'GENERIC_SCALAR_TANH_CL_PLUS_CD_POLAR_WITH_CORRIGAN_N1'; ...
    'ROOT_COLLECTIVE';'NO_HOVER_ONLY';'NO';'BETA_M_ZERO_ONLY'; ...
    'GENERIC_CONCEPT_PARAMS_NOMINAL'};
xv15={'3.81';'0.0875';'XV15_SOURCE_INFORMED_RADIAL_CHORD'; ...
    'XV15_NONLINEAR_METAL_BLADE_TWIST';'XV15_FOUR_REGION_C81_PLUS_CORRIGAN_N1'; ...
    'THETA75';'NO_HOVER_ONLY';'NO';'BETA_M_ZERO_ONLY'; ...
    'XV15_VALIDATION_INSTANCE'};
exportToGeneric={'NO';'NO';'NO';'NO';'NO';'NO';'N/A';'N/A';'N/A';'NO'};
contract=table(name,generic,xv15,exportToGeneric, ...
    'VariableNames',{'field','genericInstance','xv15ValidationInstance', ...
    'xv15ValueMayExportToGeneric'});
writetable(contract,fullfile(outputDir,'M1_MODEL_FORM_INSTANCE_CONTRACT.csv'));

% 3) Generic instance smoke point. No XV-15 data are read in this branch.
Pg.rotor.Omega=62.0;
outGeneric=rotor_m1_hover_model_form(Pg,10*pi/180, ...
    struct('instanceType','GENERIC_NOMINAL_INSTANCE'));
if ~outGeneric.physicalConverged || ~all(isfinite([outGeneric.CT,outGeneric.CP,outGeneric.FM]))
    error('audit_m1_model_form_instance_separation:GenericSmoke', ...
        'Generic nominal M1 hover instance did not produce a supported 10-deg point.');
end
genericSmoke=table(10,outGeneric.CT,outGeneric.CP,outGeneric.FM, ...
    outGeneric.thrust,outGeneric.power,outGeneric.inducedVelocity, ...
    {outGeneric.parameterBoundary}, ...
    'VariableNames',{'rootCollective_deg','CT','CP','FM','thrust_N','power_W', ...
    'inducedVelocity_mps','claimBoundary'});
writetable(genericSmoke,fullfile(outputDir,'M1_GENERIC_NOMINAL_SMOKE.csv'));

metadata=table( ...
    {'stage';'identity_gate';'xv15_parameters_exported_to_generic'; ...
     'generic_instance_parameter_source';'claim_boundary'}, ...
    {'AIRCRAFT_PROPAGATION_GATE_1';sprintf('MAX_ABS_DIFF_LE_1E-10_ACTUAL_%.12g',maxIdentityDiff); ...
     'NO';'PARAMS_NOMINAL_ONLY_PLUS_PREDECLARED_CORRIGAN_N1_MODEL_FORM'; ...
     'MODEL_FORM_TRANSFER_NOT_XV15_AIRCRAFT_VALIDATION_HOVER_ONLY'}, ...
    'VariableNames',{'name','value'});
writetable(metadata,fullfile(outputDir,'M1_MODEL_FORM_INSTANCE_METADATA.csv'));

results.identity=identity;
results.maxIdentityDiff=maxIdentityDiff;
results.contract=contract;
results.genericSmoke=genericSmoke;
results.metadata=metadata;
save(fullfile(outputDir,'M1_MODEL_FORM_INSTANCE_RESULTS.mat'),'results');
end
