function results = run_naca_tn_626_simple_rotor_validation(outputDir)
%RUN_NACA_TN_626_SIMPLE_ROTOR_VALIDATION Frozen blind simple-rotor check.
%
% Predictions are completed before Table III is read. The run uses one
% fixed 2-to-8 degree window and does not tune parameters, scan grids, or
% invoke an alternate physical model.

rootDir = fileparts(fileparts(mfilename('fullpath')));
if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(rootDir, 'results', ...
        'naca_tn_626_simple_rotor_validation');
end
if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

freezeId = 'NACA_TN626_FOUR_BLADE_SIMPLE_HOVER_V1_20260828';
claimBoundary = ...
    'SIMPLE_ISOLATED_ROTOR_CORE_COMPARISON_NOT_TEST_RIG_REPRODUCTION';
thetaDeg = (2:8).';
n = numel(thetaDeg);
Pbase = params_nominal();

%% Predict first: no Table III target is loaded above or inside this loop.
returned = false(n,1);
numericalConverged = false(n,1);
physicalConverged = false(n,1);
physicalStatus = repmat({'NOT_RUN'}, n, 1);
iterations = NaN(n,1);
closureResidualRelative = NaN(n,1);
inducedVelocity_mps = NaN(n,1);
beta0_deg = NaN(n,1);
maxAbsAlpha_deg = NaN(n,1);
thrust_N = NaN(n,1);
torque_Nm = NaN(n,1);
CT_model = NaN(n,1);
CP_model = NaN(n,1);
FM_model = NaN(n,1);
errorIdentifier = repmat({''}, n, 1);
mappingReference = struct();

for k = 1:n
    [P, mapping] = build_naca_tn_626_hover_validation_instance( ...
        Pbase, thetaDeg(k));
    if ~mapping.readiness.readyForSimpleComparison || ...
            mapping.readiness.targetsUsedInMapping
        error('run_naca_tn_626_simple_rotor_validation:MappingIncomplete', ...
            'The frozen source-to-model mapping is incomplete.');
    end

    ctrl = struct('collective', ...
        mapping.collective.modelCollective_rad, 'cyclicLong', 0);
    try
        [~, ~, out] = rotor_model_bemt_section_aero( ...
            zeros(9,1), ctrl, 0, -1, zeros(3,1), P);
        returned(k) = true;
        numericalConverged(k) = out.numericalConverged;
        physicalConverged(k) = out.physicalConverged;
        physicalStatus{k} = out.physicalStatus;
        iterations(k) = out.iterations;
        closureResidualRelative(k) = ...
            out.inducedClosureResidualRelative;
        inducedVelocity_mps(k) = out.inducedVelocity;
        beta0_deg(k) = out.beta0*180/pi;
        maxAbsAlpha_deg(k) = out.maxAbsAlphaBlade*180/pi;
        thrust_N(k) = out.thrust;
        torque_Nm(k) = out.torque;

        area = pi*P.rotor.R^2;
        tipSpeed = P.rotor.Omega*P.rotor.R;
        CT_model(k) = out.thrust/(P.env.rho*area*tipSpeed^2);
        CP_model(k) = out.torque*P.rotor.Omega/( ...
            P.env.rho*area*tipSpeed^3);
        if CT_model(k) > 0 && CP_model(k) > 0
            FM_model(k) = CT_model(k)^(3/2)/(sqrt(2)*CP_model(k));
        end
    catch ME
        expectedFailureIds = { ...
            'rotor_model_bemt:FlapNotConverged', ...
            'rotor_model_bemt:CoupledSolveNotConverged'};
        if any(strcmp(ME.identifier, expectedFailureIds))
            physicalStatus{k} = ME.identifier;
            errorIdentifier{k} = ME.identifier;
        else
            rethrow(ME);
        end
    end

    if k == 1
        mappingReference = mapping;
    end
end

%% Attach the untouched published targets only after every prediction.
sourceFile = fullfile(rootDir, 'validation', 'naca_tn_626', ...
    'NACA_TN_626_TABLE_III_FOUR_BLADE.csv');
sourceTable = readtable(sourceFile);
[found, sourceRow] = ismember(thetaDeg, sourceTable.theta_deg);
if ~all(found)
    error('run_naca_tn_626_simple_rotor_validation:SourceRowsMissing', ...
        'The frozen Table III file does not contain the full score window.');
end
conversionFactor = ...
    mappingReference.coefficientConversion.reportToStandardFactor;
CT_exp = conversionFactor*sourceTable.CT_report(sourceRow);
CP_exp = conversionFactor*sourceTable.CQ_report(sourceRow);
FM_exp = CT_exp.^(3/2)./(sqrt(2)*CP_exp);

CT_relativeError_pct = 100*(CT_model-CT_exp)./CT_exp;
CP_relativeError_pct = 100*(CP_model-CP_exp)./CP_exp;
FM_relativeError_pct = 100*(FM_model-FM_exp)./FM_exp;
freezeIdColumn = repmat({freezeId}, n, 1);
claimBoundaryColumn = repmat({claimBoundary}, n, 1);

validationTable = table(thetaDeg, CT_exp, CT_model, ...
    CT_relativeError_pct, CP_exp, CP_model, CP_relativeError_pct, ...
    FM_exp, FM_model, FM_relativeError_pct, returned, ...
    numericalConverged, physicalConverged, physicalStatus, iterations, ...
    closureResidualRelative, inducedVelocity_mps, beta0_deg, ...
    maxAbsAlpha_deg, thrust_N, torque_Nm, errorIdentifier, ...
    freezeIdColumn, claimBoundaryColumn, 'VariableNames', ...
    {'theta_deg','CT_exp','CT_model','CT_relativeError_pct', ...
    'CP_exp','CP_model','CP_relativeError_pct','FM_exp','FM_model', ...
    'FM_relativeError_pct','returned','numericalConverged', ...
    'physicalConverged','physicalStatus','iterations', ...
    'closureResidualRelative','inducedVelocity_mps','beta0_deg', ...
    'maxAbsAlpha_deg','thrust_N','torque_Nm','errorIdentifier', ...
    'freezeId','claimBoundary'});
writetable(validationTable, fullfile(outputDir, ...
    'NACA_TN_626_SIMPLE_ROTOR_VALIDATION.csv'));

%% Predeclared project screening rule; no score-window search.
expectedPointCount = n;
convergedPointCount = sum(physicalConverged);
completePhysicalWindow = convergedPointCount == expectedPointCount && ...
    all(isfinite(CT_model)) && all(isfinite(CP_model));
if completePhysicalWindow
    CT_MAPE_pct = mean(abs(CT_relativeError_pct));
    CP_MAPE_pct = mean(abs(CP_relativeError_pct));
    FM_MAPE_pct = mean(abs(FM_relativeError_pct));
    CT_meanSignedError_pct = mean(CT_relativeError_pct);
    CP_meanSignedError_pct = mean(CP_relativeError_pct);
    FM_meanSignedError_pct = mean(FM_relativeError_pct);
else
    CT_MAPE_pct = NaN;
    CP_MAPE_pct = NaN;
    FM_MAPE_pct = NaN;
    CT_meanSignedError_pct = NaN;
    CP_meanSignedError_pct = NaN;
    FM_meanSignedError_pct = NaN;
end
CT_MAPE_limit_pct = 15;
CP_MAPE_limit_pct = 20;
validationPassed = completePhysicalWindow && ...
    CT_MAPE_pct <= CT_MAPE_limit_pct && ...
    CP_MAPE_pct <= CP_MAPE_limit_pct;
if validationPassed
    verdict = {'PASS_SIMPLE_ROTOR_SCREEN'};
elseif ~completePhysicalWindow
    verdict = {'FAIL_INCOMPLETE_PHYSICAL_WINDOW'};
else
    verdict = {'FAIL_ERROR_LIMIT'};
end
window = {'PRIMARY_2_TO_8_DEG'};
metricFreezeId = {freezeId};
metricClaimBoundary = {claimBoundary};
metricTable = table(window, expectedPointCount, convergedPointCount, ...
    completePhysicalWindow, CT_MAPE_pct, CP_MAPE_pct, FM_MAPE_pct, ...
    CT_meanSignedError_pct, CP_meanSignedError_pct, ...
    FM_meanSignedError_pct, CT_MAPE_limit_pct, CP_MAPE_limit_pct, ...
    validationPassed, verdict, metricFreezeId, metricClaimBoundary, ...
    'VariableNames', {'window','expectedPointCount', ...
    'convergedPointCount','completePhysicalWindow','CT_MAPE_pct', ...
    'CP_MAPE_pct','FM_MAPE_pct','CT_meanSignedError_pct', ...
    'CP_meanSignedError_pct','FM_meanSignedError_pct', ...
    'CT_MAPE_limit_pct','CP_MAPE_limit_pct','validationPassed', ...
    'verdict','freezeId','claimBoundary'});
writetable(metricTable, fullfile(outputDir, ...
    'NACA_TN_626_SIMPLE_ROTOR_METRICS.csv'));

%% Auditable parameter pack.
parameter = {'freeze_id'; 'R'; 'Nb'; 'rootCut'; 'chord'; 'twistTip'; ...
    'rpm'; 'rho'; 'alpha0L'; 'liftSlope'; 'CLmax'; 'CD0'; ...
    'dragAlphaCoefficient'; 'kCD'; 'bladeMass'; 'Ib'; 'Sblade'; ...
    'aircraftMassForInitialGuess'; 'nRadial'; 'nAzimuth'; ...
    'inducedMaxIter'; 'inducedTol'; 'compressibilityCorrection'; ...
    'reportCoefficientConversion'};
value = {freezeId; scalar_text(mappingReference.geometry.R_m); ...
    scalar_text(mappingReference.geometry.Nb); ...
    scalar_text(mappingReference.geometry.rootCut); ...
    scalar_text(mappingReference.geometry.chord_m); ...
    scalar_text(mappingReference.geometry.twistTip_rad); ...
    scalar_text(mappingReference.testCondition.rpm); ...
    scalar_text(mappingReference.testCondition.rho_kgm3); ...
    scalar_text(mappingReference.sectionAero.alpha0L_rad); ...
    scalar_text(mappingReference.sectionAero.liftSlope_perRad); ...
    scalar_text(mappingReference.sectionAero.CLmax); ...
    scalar_text(mappingReference.sectionAero.CD0); ...
    scalar_text(mappingReference.sectionAero.dragAlphaCoefficient); ...
    scalar_text(mappingReference.sectionAero.kCD); ...
    scalar_text(mappingReference.flapMass.bladeMass_kg); ...
    scalar_text(mappingReference.flapMass.Ib_kgm2); ...
    scalar_text(mappingReference.flapMass.Sblade_kgm); ...
    scalar_text(mappingReference.initialization.aircraftMass_kg); ...
    scalar_text(mappingReference.numerics.nRadial); ...
    scalar_text(mappingReference.numerics.nAzimuth); ...
    scalar_text(mappingReference.numerics.inducedMaxIter); ...
    scalar_text(mappingReference.numerics.inducedTol); 'false'; ...
    scalar_text(conversionFactor)};
unit = {'-'; 'm'; '-'; 'r/R'; 'm'; 'rad'; 'rpm'; 'kg/m^3'; ...
    'rad'; '1/rad'; '-'; '-'; '-'; '-'; 'kg'; 'kg*m^2'; ...
    'kg*m'; 'kg'; '-'; '-'; '-'; '-'; '-'; '-'};
provenance = {'VALIDATION_FREEZE'; 'REFERENCE'; 'REFERENCE'; ...
    'MODEL_REDUCTION'; 'REFERENCE'; 'REFERENCE'; 'REFERENCE_APPROXIMATE'; ...
    'ASSUMED'; 'ASSUMED_SYMMETRIC_PROFILE'; 'REFERENCE'; 'DERIVED'; ...
    'REFERENCE'; 'REFERENCE'; 'DERIVED'; 'PLACEHOLDER'; ...
    'DERIVED_PLACEHOLDER'; 'DERIVED_PLACEHOLDER'; ...
    'INHERITED_NUMERICAL_INITIALIZATION'; ...
    'CURRENT_PRODUCTION_DEFAULT'; 'CURRENT_PRODUCTION_DEFAULT'; ...
    'CURRENT_PRODUCTION_DEFAULT'; 'CURRENT_PRODUCTION_DEFAULT'; ...
    'FROZEN_SETTING'; ...
    'DERIVED_FROM_REPORT_DEFINITION'};
parameterTable = table(parameter, value, unit, provenance);
writetable(parameterTable, fullfile(outputDir, ...
    'NACA_TN_626_SIMPLE_ROTOR_PARAMETER_PACK.csv'));

results = struct();
results.validationTable = validationTable;
results.metricTable = metricTable;
results.parameterTable = parameterTable;
results.freezeId = freezeId;
results.claimBoundary = claimBoundary;
results.noParameterTuning = true;
results.noGridScan = true;
results.targetsLoadedAfterPrediction = true;
save(fullfile(outputDir, 'NACA_TN_626_SIMPLE_ROTOR_RESULTS.mat'), ...
    'results');

fprintf('\nNACA TN 626 simple-rotor validation\n');
fprintf('Physical points: %d/%d\n', convergedPointCount, ...
    expectedPointCount);
fprintf('CT MAPE: %.6g %%\n', CT_MAPE_pct);
fprintf('CP MAPE: %.6g %%\n', CP_MAPE_pct);
fprintf('Verdict: %s\n', verdict{1});
end

function value = scalar_text(x)
value = sprintf('%.15g', x);
end
