function results = run_xv15_frozen_low_order_validation(outputDir)
%RUN_XV15_FROZEN_LOW_ORDER_VALIDATION Final frozen low-order hover check.
%
% This is the formal external comparison for the CURRENT generic low-order
% rotor equations. It is not an XV-15 reconstruction and it does not run
% any diagnostic model, parameter sweep, grid scan, or holdout tuning.
%
% Frozen interpretation:
% - OARF Run 15 supplies theta_0.75, tip speed, CT, corrected CP, and FM;
% - public XV-15 geometry is reduced to the fields already consumed by the
%   production low-order model (constant chord and linear twist);
% - scalar section-aero parameters are independently reduced from the NASA
%   CAMRAD II C81 reference inputs;
% - unresolved density and blade mass-distribution inputs retain explicit
%   generic-model assumptions and are not labelled XV-15 parameters;
% - the OARF performance targets are attached only after all predictions
%   have been computed.

rootDir = fileparts(fileparts(mfilename('fullpath')));
if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(rootDir, 'results', ...
        'xv15_frozen_low_order_validation');
end
if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

freezeId = 'XV15_LOW_ORDER_HOVER_V1_20260825';
claimBoundary = ['GENERIC_LOW_ORDER_MODEL_EXTERNAL_COMPARISON_' ...
    'NOT_XV15_REPRODUCTION_NO_HOLDOUT_TUNING'];

Pbase = params_nominal();
d2r = pi/180;
R = 3.81;
rootCut = 0.0875;

%% Frozen OARF input conditions (targets remain withheld until prediction)
pointId = {'RUN15_POINT07'; 'RUN15_POINT08'; 'RUN15_POINT09'; ...
    'RUN15_POINT10'; 'RUN15_POINT11'; 'RUN15_POINT12'; ...
    'RUN15_POINT13'; 'RUN15_POINT14'; 'RUN15_POINT15'};
theta75_deg = [0; 2; 4; 6; 7; 8; 9; 10; 11];
Vtip_fps = [769.0; 768.7; 768.4; 768.4; 768.4; 768.4; ...
    768.0; 768.0; 767.7];
n = numel(theta75_deg);

%% Independent parameter source and explicit low-order reductions
c81 = build_xv15_c81_low_order_section_aero();
frozenBladeMass_kg = Pbase.rotor.bladeMass;
frozenIb_kgm2 = frozenBladeMass_kg*R^2/3;
frozenSblade_kgm = frozenBladeMass_kg*R/2;
frozenRho_kgm3 = Pbase.env.rho;
frozenSectionAeroReady = all(isfinite([c81.alpha0L_rad, ...
    c81.liftSlope, c81.CLmax, c81.CD0, c81.kCD]));
frozenGenericMassReady = all(isfinite([frozenBladeMass_kg, ...
    frozenIb_kgm2, frozenSblade_kgm])) && ...
    all([frozenBladeMass_kg, frozenIb_kgm2, frozenSblade_kgm] > 0);
xGeom = linspace(rootCut, 1, 4001).';
twistWeights = ones(size(xGeom));
twistWeights([1 end]) = 0.5; % trapezoidal weights on the uniform stations

sourceData = struct();
sourceData.chord.reductionPolicy = 'AREA_PRESERVING';
sourceData.twist.rR = xGeom;
sourceData.twist.theta_deg = nasa_metal_twist_deg(xGeom);
sourceData.twist.weights = twistWeights;

%% One production-compatible call per test point; no alternate variants
rpm = NaN(n,1);
modelCollective_deg = NaN(n,1);
returned = false(n,1);
numericalConverged = false(n,1);
physicalConverged = false(n,1);
physicalStatus = repmat({'NOT_RUN'}, n, 1);
iterations = NaN(n,1);
inducedVelocity_mps = NaN(n,1);
closureResidualRelative = NaN(n,1);
thrust_N = NaN(n,1);
torque_Nm = NaN(n,1);
CT_model = NaN(n,1);
CP_model = NaN(n,1);
FM_model = NaN(n,1);
errorIdentifier = repmat({''}, n, 1);
mappingReference = struct();

for k = 1:n
    Vtip_mps = Vtip_fps(k)*0.3048;
    testPoint = struct();
    testPoint.rpm = Vtip_mps/R*60/(2*pi);
    % Run 15 density is not tabulated in the CR summary. Freeze the generic
    % standard-atmosphere assumption openly instead of calling it measured.
    testPoint.rho = frozenRho_kgm3;
    testPoint.theta75_deg = theta75_deg(k);

    [P, mapping] = build_xv15_v1_hover_validation_instance( ...
        Pbase, testPoint, sourceData);

    modelValidationReady = mapping.readiness.directGeometry && ...
        mapping.readiness.chordReduction && ...
        mapping.readiness.chordPolicyFrozen && ...
        mapping.readiness.twistReduction && ...
        mapping.readiness.testPointRpm && ...
        mapping.readiness.testPointRho && ...
        mapping.readiness.collectiveAdapter && ...
        frozenSectionAeroReady && frozenGenericMassReady;
    if ~modelValidationReady
        error('run_xv15_frozen_low_order_validation:MappingIncomplete', ...
            'Frozen low-order mapping is incomplete at %s.', pointId{k});
    end

    % Preserve the current model's generic uniform blade-mass assumption,
    % updated only for the frozen radius. These are not XV-15 mass data.
    P.rotor.Ib = frozenIb_kgm2;
    P.rotor.Sblade = frozenSblade_kgm;

    % All five scalar C81 reductions are frozen together here. alpha0L is
    % applied by the existing low-order section-aero wrapper; the other four
    % fields are consumed unchanged by the production rotor equations.
    P.rotor.alpha0L = c81.alpha0L_rad;
    P.rotor.liftSlope = c81.liftSlope;
    P.rotor.CLmax = c81.CLmax;
    P.rotor.CD0 = c81.CD0;
    P.rotor.kCD = c81.kCD;
    P.rotor.enableCompressibilityCorrection = false;

    rpm(k) = testPoint.rpm;
    modelCollective_deg(k) = mapping.collective.modelCollective_rad/d2r;
    ctrl = struct('collective', mapping.collective.modelCollective_rad, ...
        'cyclicLong', 0);

    try
        [~, ~, out] = rotor_model_bemt_section_aero( ...
            zeros(9,1), ctrl, 0, -1, zeros(3,1), P);
        returned(k) = true;
        numericalConverged(k) = out.numericalConverged;
        physicalConverged(k) = out.physicalConverged;
        physicalStatus{k} = out.physicalStatus;
        iterations(k) = out.iterations;
        inducedVelocity_mps(k) = out.inducedVelocity;
        closureResidualRelative(k) = out.inducedClosureResidualRelative;
        thrust_N(k) = out.thrust;
        torque_Nm(k) = out.torque;

        A = pi*R^2;
        CT_model(k) = out.thrust/(P.env.rho*A*Vtip_mps^2);
        CP_model(k) = out.torque*P.rotor.Omega/( ...
            P.env.rho*A*Vtip_mps^3);
        if CT_model(k) > 0 && CP_model(k) > 0
            FM_model(k) = CT_model(k)^(3/2)/(sqrt(2)*CP_model(k));
        end
    catch ME
        physicalStatus{k} = ME.identifier;
        errorIdentifier{k} = ME.identifier;
    end

    if k == 1
        mappingReference = mapping;
    elseif abs(mapping.chord.selectedEq_m - ...
            mappingReference.chord.selectedEq_m) > 1e-12 || ...
            abs(mapping.twist.twistTipEq_rad - ...
            mappingReference.twist.twistTipEq_rad) > 1e-12
        error('run_xv15_frozen_low_order_validation:MappingDrift', ...
            'Static frozen geometry changed between test points.');
    end
end

%% Attach untouched OARF holdout targets after prediction
CT_exp = [0.004063; 0.005581; 0.007391; 0.009208; 0.010104; ...
    0.011063; 0.012035; 0.013089; 0.013929];
CP_exp = [0.000315; 0.000426; 0.000588; 0.000796; 0.000913; ...
    0.001044; 0.001188; 0.001358; 0.001523];
FM_exp = [0.5814; 0.6921; 0.7641; 0.7849; 0.7866; ...
    0.7881; 0.7858; 0.7797; 0.7632];

CT_relativeError_pct = 100*(CT_model-CT_exp)./CT_exp;
CP_relativeError_pct = 100*(CP_model-CP_exp)./CP_exp;
FM_relativeError_pct = 100*(FM_model-FM_exp)./FM_exp;
freezeIdColumn = repmat({freezeId}, n, 1);
claimBoundaryColumn = repmat({claimBoundary}, n, 1);

validationTable = table(pointId, theta75_deg, Vtip_fps, rpm, ...
    modelCollective_deg, CT_exp, CT_model, CT_relativeError_pct, ...
    CP_exp, CP_model, CP_relativeError_pct, FM_exp, FM_model, ...
    FM_relativeError_pct, returned, numericalConverged, ...
    physicalConverged, physicalStatus, iterations, inducedVelocity_mps, ...
    closureResidualRelative, thrust_N, torque_Nm, errorIdentifier, ...
    freezeIdColumn, claimBoundaryColumn, ...
    'VariableNames', {'pointId','theta75_deg','Vtip_fps','rpm', ...
    'modelCollective_deg','CT_exp','CT_model','CT_relativeError_pct', ...
    'CP_exp','CP_model','CP_relativeError_pct','FM_exp','FM_model', ...
    'FM_relativeError_pct','returned','numericalConverged', ...
    'physicalConverged','physicalStatus','iterations', ...
    'inducedVelocity_mps','closureResidualRelative','thrust_N', ...
    'torque_Nm','errorIdentifier','freezeId','claimBoundary'});
writetable(validationTable, fullfile(outputDir, ...
    'XV15_FROZEN_LOW_ORDER_VALIDATION.csv'));

%% One predeclared primary score window; no window search
primaryMask = ismember(theta75_deg, [6; 7; 8; 9; 10; 11]) & ...
    physicalConverged & isfinite(CT_model) & isfinite(CP_model) & ...
    isfinite(FM_model);
expectedPointCount = 6;
convergedPointCount = sum(primaryMask);
if convergedPointCount ~= expectedPointCount
    error('run_xv15_frozen_low_order_validation:PrimaryWindowIncomplete', ...
        ['The frozen primary window requires %d physically converged ' ...
        'points, but only %d are available.'], ...
        expectedPointCount, convergedPointCount);
end
CT_MAPE_pct = mean(abs(CT_relativeError_pct(primaryMask)));
CP_MAPE_pct = mean(abs(CP_relativeError_pct(primaryMask)));
FM_MAPE_pct = mean(abs(FM_relativeError_pct(primaryMask)));
CT_meanSignedError_pct = mean(CT_relativeError_pct(primaryMask));
CP_meanSignedError_pct = mean(CP_relativeError_pct(primaryMask));
FM_meanSignedError_pct = mean(FM_relativeError_pct(primaryMask));
metricWindow = {'PRIMARY_6_TO_11_DEG'};
metricFreezeId = {freezeId};
metricClaimBoundary = {claimBoundary};
metricTable = table(metricWindow, expectedPointCount, convergedPointCount, ...
    CT_MAPE_pct, CP_MAPE_pct, FM_MAPE_pct, CT_meanSignedError_pct, ...
    CP_meanSignedError_pct, FM_meanSignedError_pct, metricFreezeId, ...
    metricClaimBoundary, 'VariableNames', {'window','expectedPointCount', ...
    'convergedPointCount','CT_MAPE_pct','CP_MAPE_pct','FM_MAPE_pct', ...
    'CT_meanSignedError_pct','CP_meanSignedError_pct', ...
    'FM_meanSignedError_pct','freezeId','claimBoundary'});
writetable(metricTable, fullfile(outputDir, ...
    'XV15_FROZEN_LOW_ORDER_METRICS.csv'));

%% Auditable frozen parameter pack
freezeName = { ...
    'freeze_id'; 'model_entry'; 'production_equation_entry'; ...
    'R'; 'Nb'; 'rootCut'; 'nRadial'; 'nAzimuth'; ...
    'chord'; 'chord_reduction_policy'; 'twistTip'; ...
    'alpha0L'; 'liftSlope'; 'CLmax'; 'CD0'; 'kCD'; ...
    'bladeMass'; 'Ib'; 'Sblade'; 'rho'; ...
    'compressibility_wrapper_enabled'; 'collective_reference'; ...
    'power_definition'; 'holdout_source'; 'pitch_zero_contract'; ...
    'C81_angle_zero_contract'; 'mass_property_contract'};
freezeValue = { ...
    freezeId; 'rotor_model_bemt_section_aero'; 'rotor_model_bemt'; ...
    scalar_text(R); scalar_text(3); scalar_text(rootCut); ...
    scalar_text(Pbase.rotor.nRadial); scalar_text(Pbase.rotor.nAzimuth); ...
    scalar_text(mappingReference.chord.selectedEq_m); ...
    mappingReference.chord.selectedPolicy; ...
    scalar_text(mappingReference.twist.twistTipEq_rad/d2r); ...
    scalar_text(c81.alpha0L_deg); scalar_text(c81.liftSlope); ...
    scalar_text(c81.CLmax); scalar_text(c81.CD0); scalar_text(c81.kCD); ...
    scalar_text(frozenBladeMass_kg); scalar_text(frozenIb_kgm2); ...
    scalar_text(frozenSblade_kgm); scalar_text(frozenRho_kgm3); ...
    'false'; 'OARF_THETA_AT_075R_REPORTED_AT_ZERO_RPM'; ...
    'Q_OMEGA_OVER_RHO_A_VTIP_CUBED_EQUALS_CORRECTED_CQ'; ...
    'NASA_CR_2017_219486_TABLE_A2_RUN15_POINTS07_TO15'; ...
    'STATIC_ZERO_ALIGNED_DYNAMIC_ELASTIC_TWIST_UNRESOLVED'; ...
    'STRONGLY_CHORDLINE_COMPATIBLE_NOT_EXPLICITLY_DEFINED_IN_TP'; ...
    'GENERIC_UNIFORM_BLADE_MASS_ASSUMPTION_NOT_XV15_DATA'};
freezeUnit = { ...
    '-'; '-'; '-'; 'm'; '-'; 'r/R'; '-'; '-'; 'm'; '-'; 'deg'; ...
    'deg'; '1/rad'; '-'; '-'; '-'; 'kg'; 'kg*m^2'; 'kg*m'; ...
    'kg/m^3'; '-'; '-'; '-'; '-'; '-'; '-'; '-'};
freezeProvenance = { ...
    'VALIDATION_FREEZE'; 'CURRENT_CODE'; 'CURRENT_CODE'; ...
    'NASA_PUBLIC_GEOMETRY'; 'NASA_PUBLIC_GEOMETRY'; ...
    'NASA_PUBLIC_GEOMETRY'; 'CURRENT_PRODUCTION_DEFAULT'; ...
    'CURRENT_PRODUCTION_DEFAULT'; 'EQUIVALENT_GEOMETRY_REDUCTION'; ...
    'FROZEN_MAPPING_POLICY'; 'EQUIVALENT_GEOMETRY_REDUCTION'; ...
    'NASA_C81_REFERENCE_REDUCTION'; 'NASA_C81_REFERENCE_REDUCTION'; ...
    'NASA_C81_REFERENCE_REDUCTION'; 'NASA_C81_REFERENCE_REDUCTION'; ...
    'NASA_C81_REFERENCE_REDUCTION'; 'GENERIC_MODEL_ASSUMPTION'; ...
    'GENERIC_MODEL_DERIVATION'; 'GENERIC_MODEL_DERIVATION'; ...
    'GENERIC_STANDARD_ATMOSPHERE_ASSUMPTION'; ...
    'FROZEN_WRAPPER_SETTING'; 'NASA_OARF_AND_CR_AUDIT'; ...
    'NASA_TM_86833_DEFINITION_AUDIT'; 'NASA_EXTERNAL_DATA'; ...
    'NASA_SOURCE_CONTRACT_AUDIT'; 'NASA_SOURCE_CONTRACT_AUDIT'; ...
    'MODEL_SCOPE_BOUNDARY'};
freezeStatus = { ...
    'FROZEN'; 'FROZEN'; 'UNCHANGED'; 'DIRECT'; 'DIRECT'; 'DIRECT'; ...
    'FROZEN'; 'FROZEN'; 'DERIVED'; 'FROZEN'; 'DERIVED'; 'DERIVED'; ...
    'DERIVED'; 'DERIVED'; 'DERIVED'; 'DERIVED'; 'ASSUMED'; ...
    'DERIVED_ASSUMPTION'; 'DERIVED_ASSUMPTION'; 'ASSUMED'; 'FROZEN'; ...
    'VERIFIED_WITH_LIMITATION'; 'VERIFIED'; 'HOLDOUT'; ...
    'PARTLY_UNRESOLVED'; 'PARTLY_UNRESOLVED'; 'EXPLICIT_LIMITATION'};
freezeTable = table(freezeName, freezeValue, freezeUnit, ...
    freezeProvenance, freezeStatus, 'VariableNames', ...
    {'parameter','value','unit','provenance','status'});
writetable(freezeTable, fullfile(outputDir, ...
    'XV15_FROZEN_PARAMETER_PACK.csv'));

results = struct();
results.validationTable = validationTable;
results.metricTable = metricTable;
results.freezeTable = freezeTable;
results.freezeId = freezeId;
results.claimBoundary = claimBoundary;
results.noParameterSweep = true;
results.noGridScan = true;
results.noDiagnosticModelRun = true;
save(fullfile(outputDir, 'XV15_FROZEN_LOW_ORDER_RESULTS.mat'), 'results');
end

function theta_deg = nasa_metal_twist_deg(x)
theta_deg = 289.98*x.^5 - 892.87*x.^4 + 987.06*x.^3 ...
    - 438.31*x.^2 + 15.695*x + 32.057;
end

function value = scalar_text(x)
value = sprintf('%.15g', x);
end
